- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
This pull request implements the functionality described in task #155.
Please review how I edited the `emogrify()` method to disable "inline style" parsing to ensure it was done properly.
I updated the readme and added unit tests to cover the new options that were added.
Once you merge in this pull request, would you mind tagging a 0.1.1 release?
> [FEATURE] Allow disabling of "inline style" and "style block" parsing

- Tests/Unit/EmogrifierTest.php
This will get rid of PHP strict warnings.
Fixes #166
> [CLEANUP] Make the assert calls in the tests static

- README.md
- Tests/Unit/EmogrifierTest.php
Emogrifiert always converts XHTML to HTML. This now is documented in the
README and in the unit tests.
Fixes #153
> [TASK] Document the way Emogrifier handles XHTML

- Tests/Unit/EmogrifierTest.php
- Warning about an undefined variable in the unit tests
- PHPCS warnings about opening braces not being on the next line
> [BUGFIX] Fix warnings

- Classes/Emogrifier.php
This field should be \DOMElement[], not \DOMNode[].
Fixes #186
> [CLEANUP] Change the PHPDoc type of $this->visitedNodes

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Ignore invalid CSS selectors

- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
Also keep the print media type by default.
Fixes #68
FIxes #178
> [FEATURE] Allow user to define media types to keep

- Classes/Emogrifier.php
Same as #208, but on current master.
The current master with the short array fix caused so much changes that it was easier to just start anew with this feature than try to resolve all the conflicts.
I also added the clearing of the cache, which decreases performance gains somewhat: back to ~20% from ~30%.
> [FEATURE] Cache combinedStyles

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
Included a `returnBodyContentOnly ()` function which, after called to enable the feature, will return the content of the `<body>` tag only, instead of the entire HTML.
For instance, `<!DOCTYPE html><html><head>...</head><body><p>Hello</p></body><html>` will return just `<p>Hello</p>`. This allows Emogrifier to be used on fragments of HTML code instead of entire files.
Unittests are included to test both default and feature behaviour.
If you prefer different function names, please let me know.
> emogrifyBodyContent() method, returning only the HTML within <body> tag.

- README.md
The lines in the README are now no longer than 80 characters (with
exceptions for lines with long links). This will make viewing this
file in raw format or in a diff a lot nicer on GitHub.
[ci skip]
Fixes #167
> [CLEANUP] Reformat the README

- Tests/Unit/EmogrifierTest.php
> [CLEANUP] Use PHP_EOL instead of LF in the unit tests

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
Add s modifier to regex so . matches newline. And break so a query
is only added once.
Fixes #234
> [BUGFIX] Fix multi-line media queries

- README.md
* document that the mbstring PHP extension is required
* remove that !important is not supported (as we already support for it)
[ci skip]
> [TASK] Some documentation fixes

- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Fix first-child and last-child selectors

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
Revert to splitting declaration blocks using a regex.
Split on ; except when it is followed by charset or base64.
Make the validation of property/value pairs and surrounding white space more
robust.
Fixes #258
> [BUGFIX] Parsing CSS declaration blocks

- .travis.yml
Temporarily allow failures with PHP 7.0 as the sniffs from the
TYPO3SniffPool are not found in PHP 7.0:
https://github.com/typo3-ci/TYPO3SniffPool/issues/78
> [BUGFIX] Allow Travis failures with PHP 7.0

- .travis.yml
Currently, the code sniffer will not execture on PHP 7 as it fails to load
the sniffs from the TYPO3 sniff pool. Instead of allowing the PHP 7 build
to fail, we now skip the code sniffer for PHP 7, still allowing the linter
and unit tests to run with PHP 7.
Fixes #289
> [TASK] Skip PHP_CodeSniffer on PHP 7

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] First-child and last-child selectors are broken

- CHANGELOG.md
- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
Ignores CSS statements of the form "el:pseudoclass::pseudoelement"
where "pseudoclass" is a supported selector such as ":last-child"
and pseudoelement is an unsupported selector such as "::after".
Fixes #308
> [BUGFIX] Ignore pseudo-class when combined with pseudo-element

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Allow spaces around the > in the direct child selector

- Tests/Unit/EmogrifierTest.php
- remove the document type from the HTML in the tests where the
document type is not relevant
- inline $html and $css to make the tests more succinct
Fixes #137
> [CLEANUP] Simplify the doctype handling in the tests

- .travis.yml
- CHANGELOG.md
- Tests/Unit/EmogrifierTest.php
HHVM in PHP-7 mode breaks Composer.
Other big projects are dropping support for HHVM due to these issues, too.
> [TASK] Drop support for HHVM

- .travis.yml
As the code sniffer is executed for all PHP versions, we do not need a
version-dependent condition for it anymore.
> [CLEANUP] Drop the condition for sniffing the code

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
Fix InvalidArgumentException when xpath does not find the css selector (eg: css3 keyframes).
You can reproduce the InvalidArgumentException using the following css :
```css
@-moz-keyframes animate-stripes{
0% {background-position: 0 0;} 100% {background-position: 60px 0;}
}
```
> Fix InvalidArgumentException

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
IMPORTANT! This fix may be a breaking change (depending on the input)!
Right now, original inline style rules are left at the beginning of the
final inline style string, which may be wrong in some cases
Consider
`<style>p {padding:10px}</style>`
`<p style="padding-left:20px"></p>`
This results in
`<p style="padding-left:20px;padding:10px"></p>`
which is wrong.
This fix helps to reverse priorities and it outputs
`<p style="padding:10px;padding-left:20px"></p>`
(Some existing tests had to be modified too...)
> Make inline style priority higher than css block priority

- Tests/Unit/EmogrifierTest.php
- remove superfluous words from test names
- make the tests for adding HEAD and HTML by default clearer
- add a test case about not adding the BODY element
> [CLEANUP] Simplify and clean up the test case (part 1)

- Classes/Emogrifier.php
This makes sure the code is not changed by a reformat with PhpStorm.
> [CLEANUP] Minor code reformat

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
Here is another PR with 2 small fixes regarding mapped HTML attributes:
- Original inline styles were not considered before
- Final "auto" values were not considered before
Please note that PR may introduce breaking changes.
> [BUGFIX] Fixed mapped html attribute values

- README.md
- link the selectors to the corresponding reference page in the MDN
- sort the selectors the same way they are sorted in the MDN
- use sub-lists for attribute and pseudo-element selectors
Also fix a small typo.
[ci skip]
> [CLEANUP] Rework the selector list in README.md

- CHANGELOG.md
There is a redirect from the old to the new repository location.
Always using the new links will skip this redirect, making the links
faster for the user.
> [CLEANUP] Convert all GitHub links to the new location

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
This solves issue https://github.com/MyIntervals/emogrifier/issues/378,
although I consider this is not a bugfix, but enhancement (which in the
same time happens to fix incorrect behaviour of some email clients).
It was implemented as an option (`$shouldRemoveImportantAnnotation`) and
it is enabled by default, because it renders output simpler, while keeping
it 100% compatible with old output.
> [FEATURE] Remove `!important` from final inline style declarations

- CHANGELOG.md
- Tests/Unit/EmogrifierTest.php
This makes debugging failing tests easier as Emogrifier then will throw an
exception instead of failing silently on selectors that are not
recognized.
> [TASK] Always enable the debug mode in the tests

- Tests/Unit/EmogrifierTest.php
- simplify tests for attribute value matchers
- shorten data set names a bit
- note attribute matchers that still are broken
> [CLEANUP] Simplify and clean up the test case (part 6)

- Classes/Emogrifier.php
- README.md
Now the order of the rules match the order of the supported selectors in
the README (with one exception, which is documented).
Also now the comments for the rules match the descriptions in the README,
and the README has short explanations for the different attribute matchers.
> [CLEANUP] Reorder and comment the xPath matching rules

- .travis.yml
- CHANGELOG.md
- composer.json
This ensures that our dependency versions given in the composer.json always
provide a working set of packages.
Also make the development dependencies more lenient.
Fixes #394
> [TASK] Test with latest and oldest dependencies on Travis

- .travis.yml
- Classes/Emogrifier.php
- Configuration/PhpCodeSniffer/Standards/Emogrifier/ruleset.xml
- composer.json
Also use the new whitelisting syntax and make use of two newly-available
sniffs.
> [TASK] Update PHP_CodeSniffer to 3.2.x

- Configuration/PhpCodeSniffer/Standards/Emogrifier/ruleset.xml
While Emogrifiert currently does not have any code that is affected by this
sniff, this sniff will complain about perfectly well-formatted code
(as seen in another project).
> [BUGFIX] Remove the Generic.Arrays.ArrayIndent sniff

- .travis.yml
- remove the GitHub auth token as we won't run into limits
anymore now that we usually cache Composer data
- remove the check for the existence of xdebug.ini
as it always will exist
> [TASK] Slim down the .travis.yml

- CHANGELOG.md
- Classes/Emogrifier.php
- README.md
> [TASK] Deprecate the removal of invisible nodes

- CHANGELOG.md
- Classes/Emogrifier.php
- README.md
Nowadays, we can expect email clients to understand CSS reasonably well.
So converting CSS non-CSS HTML attributes will not be needed anymore.
> [TASK] Deprecate enableCssToHtmlMapping

- Classes/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- Tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- Tests/Unit/Emogrifier/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
This class will be the base class for other classes that can remove
invisible nodes, convert CSS to non-CSS attributes etc.
The folder structure will be cleaned up once the Emogrifier class has
been renamed to CssInliner and moved from the Pelago\ namespace to the
Pelage\Emogrifier namespace (which will happen in Emogrifier 4.0.0).
> [FEATURE] Add an AbstractHtmlProcessor class

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
This is the recommended way to access static attributes and methods
as this will take subclasses into account.
> [CLEANUP] Convert self:: to static::

- Classes/Emogrifier.php
- Classes/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Exception codes bigger or equal than 2^31 will throw an error on x86 systems (or x86 builds):
```
Error: Wrong parameters for InvalidArgumentException([string $message [, long $code [, Throwable $previous = NULL]]])
```
> [BUGFIX] Make all exception codes 32-bit compatible

- Tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
It seems that `DOMDocument::saveHTML()` uses `\n` instead of platform-specific EOL character(s). This means that on non-*nix systems (i.e. Windows), `PHP_EOL` cannot be used to verify its output.
It causes `AbstractHtmlProcessorTest::reformatsHtml()` failure.
> [BUGFIX] Corrected expected HTML string EOL separator

- .github/CONTRIBUTING.md
- .travis.yml
- composer.json
Command is defined in a single place (composer.json) and if it ever needs
to be modified, it has to be modified in one place.
To run PHPUnit tests simply use command `composer test`.
(Next: composer command for phpcs too.)
> [ENHANCEMENT] Use composer script to run unit tests

- .github/CONTRIBUTING.md
- .travis.yml
- composer.json
Running PHP_CodeSniffer is now more developer-friendly: `composer phpcs`.
> [FEATURE] Use composer script to run phpcs

- .github/CONTRIBUTING.md
- .travis.yml
- CHANGELOG.md
- composer.json
The script names should be named so that we can add integration tests
and configuration file linting while keeping consistent script names
without having to rename the existing scripts.
> [TASK] Make the Composer CI sniffs more future-proof

- tests/Unit/EmogrifierTest.php
Moved the reusable test HTML with various elements, IDs, classes and attributes
to a constant.
> [CLEANUP] Move common test HTML to a constant

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Added the 's' (PCRE_DOTALL) pattern modifier for `preg_match` in
`parseCssDeclarationsBlock` so that property values containing newlines are also
matched.  Added PHPUnit tests for such property values.
> [BUGFIX] CSS property values with newlines dropped

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Changed `$xPathRules` regular expression for adjacent sibling combinator to
match zero or more spaces either side, rather than one or more, allowing
selectors with this combinator in minified CSS to be matched.  Added PHPUnit
tests for such CSS.
>  [BUGFIX] Minified adjacent sibling combinator

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Changed CSS-to-XPath translation matcher for descendant combinator to exclude
only spaces within `[...]`, i.e. when not followed by a closing `]` unless there
is an intervening opening `[` (rather than than excluding any space where the
remaining part of the expression ends with a closing `]`).  This matches spaces
in the original CSS selector but not spaces in already-translated XPath
predicates, and allows attribute selectors to be used in descendants.
Added PHPUnit tests for some attribute selectors as descendants, particularly
where the translated XPath predicate will contain a space.  Also added tests for
the converse (attribute selectors with descendants), and comments for relevant
tests that should be added but would currently fail due to other issues.
This should fix Issue …
> [BUGFIX] Descendent attribute selectors

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Filter out `@charset` at-rules from the CSS before processing, to avoid an error
when presented with CSS containing this at-rule.
Obviously this does not mean `@charset` is supported - its value is still
ignored - but does address the immediate error in #296.
Added PHPUnit test like that for `@import`, and also test that such CSS content
does not prevent Emogrifier working correctly on the remainder of the CSS.
> [BUGFIX] Allow @charset without error

- tests/Unit/EmogrifierTest.php
Corrected duplicated missing ">" typo in boilerplate HTML used by several tests,
adding common method for setting such HTML in the test subject.
Needed before adding additional test using this HTML for #508.
> [CLEANUP] Boilerplate HTML for tests

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Fix for style property ordering when multiple mixed individual and shorthand
properties apply (#508).
In `generateStyleStringFromDeclarationsArrays`, an overridden style was
retaining its original position in the property list from the result of
`array_merge`, which could be before a shorthand/individual variant it should
apply after.
The properties that are overridden are now `unset` from the arrays before the
`array_merge`, so that the correct order is maintained.
> [BUGFIX] Individual/shorthand style property order

- tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Ensured there's at least one property declaration in CSS rule blocks used with
@media rule tests, as changes for #280 will result in elimination of empty CSS
rule blocks during processing.
> [CLEANUP] Nonempty rule blocks for @media tests

- tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
In tests using `assertNotContains`, assert only that a minimal string sufficient
to indicate a test failure is not present.
Changes for #280 will inevitably mean that during processing, due to the way
that some components of the CSS are `trim`med, some unnecessary whitespace is
removed from the CSS for media queries added to the style element.  Thus
asserting that a complete media query rule is not present in the result may
allow a test to pass that should fail.  Asserting that just, e.g., "@media" or
"@media tv" is not present in the result gives a more stringent test.
For completeness, needles used with `assertNotContains` in other tests have also
been similarly shortened.  Some of these tests would have allowed invalid
passes, e.g. with a semicolon at the end of a style attribute that …
> [CLEANUP] Tighten tests using `assertNotContains`

- CHANGELOG.md
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
This allows chaining multiple HtmlProcessory without the performance
penalty of serializing to HTML and then parsing the HTML into a
DOMDocument for each processor.
> [FEATURE] Expose the DOMDocument in AbstractHtmlProcessor

- tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Added test assertion methods similar to `assertContains` and `assertNotContains`
but which also allow for removal of some unnecessary whitespace from the CSS,
without having to make the test data less humanly readable or change the test
inputs.
Changes for #280 will inevitably mean that during processing, due to the way
that some components of the CSS are `trim`med, some unnecessary whitespace is
removed from the CSS for media queries added to the style element.  Relevant
tests have been changed to used the new assertion methods.
> [CLEANUP] Allow whitespace removal in @media tests

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
This interface change the is first step toward having CssInliner
inherit from AbstractHtmlProcessor.
> [TASK] Remove the $css parameter from the CssInliner constructor

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
In `splitCssAndMediaQuery` corrected the cleaning regex to also remove at-rules
even if they are not at the start of a line (removing no-longer/not needed PCRE
modifiers, and for performance using possessive quantifiers where possible).
> [BUGFIX] At-rules not at start of line

- tests/Support/Traits/AssertCss.php
- tests/Unit/Support/Traits/AssertCssTest.php
Allow the direct use, in test result assertions, of input strings containing
whitespace at the start of the CSS.
This will be required for testing around an issue involving handling of
whitespace in @media query string-matching regex.
> [CLEANUP] Allow test CSS input whitespace at start

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Corrected regular expression for splitting out @media rules from the CSS not to
include disallowed media types with extra whitespace before the type.
> [BUGFIX] @media query with extra whitespace

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Corrected regular expression for splitting out `@media` rules from the CSS not
to consume a subsequent `@media` rule after an empty one.
Similarly corrected the regular expression cleaning the unneeded `@media` rules,
using a common subexpression for matching a `@media` rule body.
(Found while working on #280, as the regular expression would match `"@media
screen {} @media tv { h1 { color: red; } }"` as a single `@media` rule, causing an
issue parsing its presumed rule body later.)
> [BUGFIX] @media rule after empty @media rule

- src/Emogrifier/CssConcatenator.php
- tests/Unit/Emogrifier/CssConcatenatorTest.php
This abstracts the (re-)combining of CSS rules for various media queries and
with various selectors and declaration blocks, merging adjacent rule blocks
where possible (i.e. for the same media query, with the same selectors, or with
the same declarations block).
Although not yet utilized, it will be required for #280 to simplify the code.
> [CLEANUP] Add a CssConcatenator class

- tests/Support/Traits/AssertCss.php
- tests/Unit/Support/Traits/AssertCssTest.php
Allow varying whitespace around commas (in selector list separators) in
`AssertContainsCss`, etc.
This will be required for testing that CSS rules with state-based pseudo-classes
are copied to the style element for #280.
> [CLEANUP] AssertCss - whitespace around comma

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
This refactoring reduces the complexity of the process method.
> [CLEANUP] Extract method: copyInlineableCssToStyleNode

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Copy CSS for selectors involving pseudo-elements and dynamic (state-based)
pseudo-classes to the style element added to the document (along with the media
queries).
`parseCssRules`:
- Include rules for such selectors in the "uninlineable" rules array (instead
of discarding them), flagging them with "hasUnmatchablePseudo";
- Don't consider selectors with both an unsupported and a supported
pseudo-class as matchable for inlining styles.
`copyUninlineableCssToStyleNode`:
- Strip the unmatchable pseudo-components from selectors before calling
`existsMatchForCssSelector`.
Various unit tests added.
This addresses #280 for the `Emogrifier` class.
> [FEATURE] Selectors with states & pseudo-elements

- CHANGELOG.md
- config/PhpCodeSniffer.xml
Note:
`<exclude name="Squiz.Commenting.FunctionComment.ScalarTypeHintMissing"/>`
would not be required if `<config name="php_version" value="50500"/>` was
present, but the latter would probably have further-reaching consquences and
PHP 5 support will be deprecated soon.
Closes #563.
> [TASK] Add sniff for type hinting

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
This is the next step toward making `CssInliner` inherit from
`AbstractHtmlProcessor`.
Part of #554
> [FEATURE] Add CssInliner::render

- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Also restructure the code so that the PhpStorm code autoformatting
will not create any PHP_CodeSniffer warnings.
Part of #403
> [CLEANUP] Simplify and clean up the test case (part 9)

- .travis.yml
- CHANGELOG.md
- composer.json
- config/PhpCodeSniffer.xml
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
Also fully-qualified the global namespace in a few function call instances that
were missed in #573.
This change makes available all Slevomat PHPCS sniffs
(https://github.com/slevomat/coding-standard), via Composer and the config XML,
should any others of them also be desired in future.
However, as Slevomat requires PHP 7, PHPCS is now skipped for the CI build with
earlier PHP versions (it only really needs to run against one PHP version).
Part of #574.
> [TASK] Sniff for FQN in global function calls

- config/PhpCodeSniffer.xml
This change just updates the comment in the PHPCS config XML to indicate that
@param and @throws descriptions which are not full sentences (and thus do not
have a capital letter or full stop) are allowed - rather than something to be
fixed.
Related to #574.
> [CLEANUP] Allow PHPDoc without full sentences

- .travis.yml
- CHANGELOG.md
- composer.json
- config/PhpCodeSniffer.xml
- Install `slevomat/coding-standard` only for PHP 7.x in Travis.
- Delete `Squiz.PHP.ForbiddenFunctions` (`Generic.PHP.ForbiddenFunctions`)
- Enable installation on `~7.3.0`
Releated issue: #585
> Fix Travis for PHP 5.x

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/Support/Traits/AssertCssTest.php
Hyphens need to be escaped in regular expressions. Because of that tests will be falling in PHP 7.3
Error from tests:
```
Warning: preg_replace(): Compilation failed: invalid range in character class at offset 39 in /builds/php/mailing/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 1507
```
See:
https://stackoverflow.com/questions/26208622/preg-match-compilation-failed-invalid-range-in-character-class-at-offset-15?rq=1
> Escape hyphens in regular expressions

- CHANGELOG.md
- composer.json
This makes sure that composer will only install Emogrifier if the
library is present.
> [BUGFIX] Add required DOM PHP extension to `composer.json`

- composer.json
- phpcs.xml.dist
Now the file is in the default location, allowing it to be used without
explicitly specifying the standard.
> [CLEANUP] Move the PHP_CodeSniffer configuration

- .travis.yml
`composer update` by default installs the latest dependencies. So
we only need a parameter if we want to install the oldest versions of
the dependencies.
> [CLEANUP] Simplify the dependencies installation

- composer.json
This is the 1.2.x backport of #602.
> [BUGFIX] Increase PHP_CodeSniffer version for PHP compatibility

- composer.json
Copy the current list of authors and the support links from the master
version of the `composer.json` to the 1.2.x branch so the data on
Packagist for the next 1.2.x release will be correct.
[ci skip]
> [TASK] Update the authors and support linkgs in the `composer.json`

- .github/CONTRIBUTING.md
- .gitignore
- CHANGELOG.md
- composer.json
- config/php-cs-fixer.php
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
As the fixer should fix the files in multiple directories, the
`--config` argument is required, which removes the benefits of
storing the configuration in the default `.php_cs.dist`.
Also autoformat the code with the fixer.
> [FEATURE] Add a Composer script for PHP CS Fixer

- .travis.yml
The switch for installing the oldest/newest dependencies should also
be applied when installing slevomat/coding-standard.
> [BUGFIX] Consistently use the Composer dependencies preference

- .travis.yml
- composer.json
This reduces the amount of typing required for Composer updates.
This does not affect projects that use Emogrifier as a library,
but only stand-alone installations of Emogrifier (usually for
development).
> [CLEANUP] Move the prefer-stable/dist to `composer.json`

- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
Thus, we can avoid quoting single quotes and using the LF constant.
> [CLEANUP] Use double quotes for strings where appropriate

- .github/CONTRIBUTING.md
Following #576 and #589, the dependencies for PHP_CodeSniffer now require
PHP 7.0, but cannot be included in `composer.json` while PHP 5.x is still
supported, so an extra Composer installation step is now required.
> [TASK] Document PHPCS dependencies install step

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Now that the DOM document is stored in a field, there is no need to pass it
around as a parameter.
> [TASK] Stop passing the DOM document around

- .github/CONTRIBUTING.md
Now that we can squash on merge, the contributors do not necessarily
need to squash their commits anymore.
> [TASK] Remove the git squash from the contribution guidelines

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- Change `$domDocument` to `$this->domDocument` in some places in the PHPDoc
that the previous change had missed.
- Reset state first thing in `process()`.
> [CLEANUP] Streamline the process methods

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
The new name makes the difference to `createRawDomDocument` more clear.
Part of #554.
> [TASK] Rename `createDomDocument` to `createUnifiedDomDocument`

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
This is another step towards making the `CssInliner`
an `HtmlProcessor`, preparing for the DOM document
getting created directly when the HTML is set.
Also make the corresponding methods in `AbstractHtmlProcessor`,
`CssInliner` and `Emogrifier` more similar to each other.
> [TASK] Pass the HTML around for processing

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Also make the parts where the HTML is set more similar to the
corresponding places in the `AbstractHtmlProcessor` class.
Part of #554.
> [TASK] Build the DOM directly when setting the HTML

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
This is another step towards making the `CssInliner`
an `HtmlProcessor`, i.e., part of #554.
> [FEATURE] Add Emogrifier/CssInliner::getDomDocument

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- Add a (protected) `render()` method to the `Emogrifier` class.
- Use the `render()` method where it can be used.
- Change the tests in `CssInlinerTest` to use `render()` instead of
`emogrify` if they actually are about the rendering, not the
emogrification.
- Streamline some PHPDoc annotations.
This change work towards splitting `emogrify()` into `inlineCss()` and
`render()`in `CssInliner`.
Part of #554.
> [TASK] Consistently use the render() method

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
For `CssInliner` and `AbstractHtmlProcessor`, this method is part of the
public API. For `Emogrifier`, it is internal.
This is part of #554.
Also autoformat the changed classes, fix a typo in a test name, and remove
the check for the existence of the BODY element from `getBodyElement()`
(as this always is ensured and hence will never happen).
> [FEATURE] Add a renderBodyContent() method

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
Composer already has information about the currently installed version
of Emogrifier, and https://github.com/Ocramius/PackageVersions
provides a way to programmatically retrieve the version.
For visual inspection, there is `CHANGELOG.md`.
Closes #636
> [TASK] Drop the `@version` PHPDoc annotations

- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
The new test shows that issue #646 only affects attribute values, not text
nodes.
> [TASK] Add test for keeping curly braces in text nodes

- CHANGELOG.md
- src/Emogrifier.php
This looks like a victim of find and replace when static attribute
accessor was changed from `self` to `static`
https://github.com/MyIntervals/emogrifier/commit/d11de626d94593c4933e2f172e0ba0dcf846befb#diff-cc9a3a01aba196708dfca8c47b5fd06eR1587
> Fix invalid output of `translateNthChild`

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Not all ‘unprocessable’ tags (`<wbr>` by default) were being removed, because a
‘live’ NodeList was being iterated.  This was a regression as a result of #627.
Also modified related tests to include a `<body>` element in the input HTML.
Prior to #627, `removeUnprocessableTags()` did not behave as documented – if
elements had content it would still remove the tags (though not the content).
The tests did not pick this up because `DOMDocument::loadHTML()` creates a
`<body>` element if there isn’t one, and if there is text content (at the start)
not inside any element, wraps it in a `<p>` element
(https://secure.php.net/manual/en/domdocument.loadhtml.php#88864).  (It does not
create a `<p>` element if there is already a `<body>` element.)
> [BUGFIX] Remove all ‘unprocessable’ tags.

- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
Added support to `AbstractHtmlProcessor` for HTML5 self-closing tags not
recognized as such by PHP’s `DOMDocument` implementation.  In effect this is a
workaround for the issue reported in https://bugs.php.net/bug.php?id=73175.
Affected tags require a self-closing slash in the HTML input to `DOMDocument`
(e.g. `<wbr/>` rather than `<wbr>`), and their invalid corresponding closing tag
(e.g. `</wbr>`) removing from its HTML output.
Follows from discussion in #650.
> [BUGFIX] `AbstractHtmlProcessor`: HTML5 void tags

- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
Added support to `CssInliner` for HTML5 self-closing tags not recognized as such
by PHP’s `DOMDocument` implementation.  This is a direct port of the equivalent
changes made for `AbstractHtmlProcessor` in #651.
> [BUGFIX] `CssInliner`: Support HTML5 void tags

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
Added support to `Emogrifier` for HTML5 self-closing tags not recognized as such
by PHP’s `DOMDocument` implementation.
This is a port of the equivalent changes made for `AbstractHtmlProcessor`
in #651, with some differences in the tests:
- The tests employ `emogrify` and `emogrifyBodyContent` rather than `render` and
`renderBodyContent`, as the latter are not public methods;
- Since, by default, `emogrify` removes `<wbr>` elements, an additional call to
`removeUnprocessableHtmlTag()` is required in each test’s set-up;
- An additional separate test confirms `removeUnprocessableHtmlTag('wbr')`
behaves as expected.
> [BUGFIX] `Emogrifier`: Support HTML5 void tags

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
This is another step toward making `CssInliner` a `HtmlProcessor`.
> [TASK] Separate CssInliner::inlineCss and the rendering

- config/php-cs-fixer.php
- tests/Support/Traits/AssertCss.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/CssConcatenatorTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
- tests/Unit/EmogrifierTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
This communicates that the test classes are not intented to be subclassed.
(Also, it is a bit shorter.)
> [CLEANUP] Use self:: instead of static:: in the tests

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
The encoding will be reset a few lines later with the
`loadHTML` call anyway.
> [CLEANUP] Stop setting DOMDocument->encoding

- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
This makes sure that these characters are properly retained when reading
and re-creating the HTML.
> [TASK] Add Japanese characters to the UTF8-relatet tests

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
This call is not needed directly after the call to `loadHTML` as the
latter call normalized the HTML, too.
> [CLEANUP] Stop calling DOMDocument->normalizeDocument

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
Following #651/#652, there is now no need to remove `<wbr>` elements by default
as they are now correctly processed.  For backwards compatibility, the behaviour
is not changed for `Emogrifier`; it is only changed for `CssInliner` which is a
new class.
> [TASK] `CssInliner`: Keep `<wbr>` tags by default

- CHANGELOG.md
- src/Emogrifier/CssConcatenator.php
In `CssConcatenator`, create `callable` for `static` method using `static::class` not `$this`.
(Spotted in #669.  Instances of `static` methods being called through `$this` were previously corrected in #525.)
> [CLEANUP] Call static methods statically

- .travis.yml
Also properly quote the PHP version strings in the `.travis.yml`.
> [BUGFIX] Fix the installation of PHP 5.5 on Travis CI

- .gitattributes
- CHANGELOG.md
Mark all development-only files and directories as `export-ignore`
via the `.gitattributes` file. This will keep them from being packaged
in the release ZIPs provided by GitHub and in the packages downloaded
by Composer with the `--prefer-dist` option (which is the default).
> [BUGFIX] Keep development files out of the Composer packages

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
…returned by `renderBodyContent` or `emogrifyBodyContent`.
Fixes #677
> [BUGFIX] Remove body tag with attribute from content

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/HtmlPruner.php
- tests/Unit/CssInlinerTest.php
Also copy the comment that explains the used XPath expression from the
removed method to the corresponding constant in `HtmlPruner`.
Also add some missing code markup to a recently added line in the
changelog.
> [TASK] Drop the removal of invisible nodes from CssInliner

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
Now that 'CssInliner' properly can handle HTML5 tags, this functionality
is not needed anymore.
Closes #682
> [TASK] Drop the removal of unprocessable tags from CssInliner

- .travis.yml
- CHANGELOG.md
- composer.json
- config/php-cs-fixer.php
> [TASK] Drop support for PHP 5.5

- CHANGELOG.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [TASK] Add unit tests for nth-child and nth-of-type

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
This was causing an error because `removeUnmatchablePseudoComponents()` was
converting the selector to `:not()`, which is invalid.  The intention would have
been to convert it to `:not(*)`, but this is not correct either.  If a
behavioural pseudo-class is used within the `:not` argument, then the entire
`:not(…)` component should be stripped in order to test whether the selector
could match any DOM elements.
> [BUGFIX] Allow `:not(:behavioural-pseudo-class)`

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
> [TASK] Make the $css parameter of the inlineCss method optional

- CHANGELOG.md
- README.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
- src/Emogrifier/HtmlProcessor/HtmlNormalizer.php
The `CssInliner` class now is not a tech preview anymore, and it should
be used instead.
The documentation in the README will be enhanced and polished even more
in a separate change.
Closes #680
Part of #695
> [TASK] Deprecate the Emogrifier class

- README.md
Now there is only one section explaining how to install Emogrifier
with Composer, not two.
> [CLEANUP] Drop redundant README section on installation

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Although `parseCssRules()` drops rules with empty declarations blocks, those
which contain non-whitespace but no actual parsable declarations are retained,
as the declarations themselves are parsed later – (indirectly) by
`copyInlineableCssToStyleAttribute()`.  An additional check is now made in that
method.
(Also removed a trailing EOL whitespace in the CHANGELOG.)
Fixes #259.
> [BUGFIX] Don’t create empty `style` attributes

- CHANGELOG.md
- src/Emogrifier.php
- tests/Unit/EmogrifierTest.php
This is a port of #697 to the `Emogrifier` class.
> [BUGFIX] Allow `:not(:pseudo)` with `Emogrifier`

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
Part of #380.
The basic functionality of the method is unit-tested.  More extensive unit tests
involving all kinds of CSS rules and HTML already exist for testing the full
content of the `<style>` element containing the uninlinable rules.
> [FEATURE] Add CssInliner::getMatchingUninlinableSelectors

- CHANGELOG.md
- tests/Unit/CssInlinerTest.php
Implemented these tests that were previously commented as “broken”, and added a
test for presence of a Boolean attribute.  They have been fixed by virtue of
using the Symfony CssSelector component.
Resolves #375.
> [TASK] Test descendant attribute selectors

- CHANGELOG.md
- src/Emogrifier/Utilities/ArrayIntersector.php
- src/Emogrifier/Utilities/CssConcatenator.php
> [TASK] Mark the utility classes as internal

- CHANGELOG.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Closes #443.  This was actually fixed by #506.  The tests added for `Emogrifier`
confirm this for the specific case; those (same) added for `CssInliner` confirm
there’s no similar issue with the Symfony CssSelector component.
> [TASK] Test descendant attribute prefix selector

- CHANGELOG.md
- src/Emogrifier/HtmlProcessor/HtmlPruner.php
- src/Emogrifier/Utilities/ArrayIntersector.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
> [FEATURE] Add HtmlPruner::removeRedundantClasses

- CHANGELOG.md
Copied the relevant CHANGELOG entry from previous releases into the ‘x.y.z’
section so that it will appear in the 3.0 release note.
> [CLEANUP] Mark PHP 5.6 as deprecated for 3.0 release

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
The proposed solution in #334 for retaining `@import` rules has a flaw: it may
keep such rules that were commented-out.
By separating out the comment removal from other CSS parsing, we can avoid that
pitfall.
Also optimized the regex for CSS comments by unfolding and using possessive
quantifiers, potentially avoiding catastrophic failure.
Part of #338.
> [CLEANUP] Move CSS comment removal to separate method

- CHANGELOG.md
- tests/Unit/CssInlinerTest.php
Also `:not(type)`.  There were placeholder comments “broken: …” for these tests.
The selectors are now supported by virtue of using the Symfony CssSelector
component.
Resolves #469.
> [TASK] Test `:not(.class)` (as entire selector)

- CHANGELOG.md
- README.md
- src/Emogrifier/HtmlProcessor/HtmlPruner.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
Also added section for `HtmlPruner` to the README.
Closes #380.
> [FEATURE] Add HtmlPruner::removeRedundantClassesAfterCssInlined

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/Utilities/CssConcatenator.php
`static::` should only be used where overriding the corresponding
method/field is intended.
This makes the intent of the code more clear. (And in addition,
`self::` is a bit shorter than `static::`.)
Fixes #730
> [CLEANUP] Replace most `static::` with `self::`

- CHANGELOG.md
- README.md
- src/Emogrifier/HtmlProcessor/HtmlPruner.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
The additional part of the XPath expression was obtained by running
`:not(.-emogrifier-keep)` through `CssSelectorConverter::toXPath()`.  It tests
for attribute presence before checking the value, presumably as an omptimization
to avoid unnecessary processing of a null/empty value.  On the presumed basis
that this is a good idea, a similar check has been added for the `style`
attribute.
Resolves #252.
> [FEATURE] Keep `display:none` elements with `-emogrifier-keep`

- CHANGELOG.md
- README.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Also added “broken: …” placeholder comments for tests that would currently fail
due to lack of support, and updated the README to reflect the level of support
for the universal selector.
Part of #723.
> [TASK] Test universal selector with combinators

- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Added “broken: …” comments as placeholders for case-insensitive attribute
selector tests that would currently fail due to lack of support.  This indicates
that the lack of support has been confirmed (e.g. with the Symfony CssSelector
component).
Part of #723.
> [TASK] Placeholder for case-insensitive attribute tests

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
The regular expression in `PSEUDO_CLASS_MATCHER` would match, e.g.,
`:hover:first-child` as a supported pseudo-class because it was consuming any
non-space character as being valid in a pseudo-class name.  This has been
corrected so that it only consumes ‘word’ characters and hyphens.
> [BUGFIX] Dynamic and static pseudo-class combined

- README.md
This updates the list to those that are supported **and** for which we have
tests.  There are some others that are (probably) supported but for which we
don’t yet have any tests – see #747 – these have not been added to the list …
yet.
Part of #723.
> [TASK] Update supported pseudo-classes in README

- CHANGELOG.md
- README.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Also updated the regex for supported pseudo-classes (`PSEUDO_CLASS_MATCHER`) so
that those supported are explicitly specified (rather than ‘anything ending with
`-child` or anything ending with `-type(`’), without acually affecting the valid
pseudo-class names it will match.  Except in the `Emogrifier` class – this
doesn’t support `:nth-last-child` so that has been removed (to the effect that
rules with it will now be copied to the `<style>` element rather than attempted
to be inlined).
And added `:nth-last-child` to the list of supported pseudo-classes in the
README.  (Also, for consistency, added `()` to the other `:nth…` pseudo-classes
in that section.)
Part of #747.
> [TASK] Test :nth-last-child

- CHANGELOG.md
Where tests have been added, two were for new features by virtue of using the
Symfony CssSelector component.  This is now more clearly indicated in the
CHANGELOG.
> [CLEANUP] Indicate new features in CHANGELOG

- CHANGELOG.md
- README.md
- src/Emogrifier.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Also removed it from the regex for supported pseudo-classes
(`Emogrifier::PSEUDO_CLASS_MATCHER`) for the legacy `Emogrifier` class which
does not support it (to the effect that rules with it will now be copied to the
`<style>` element rather than attempted to be inlined).
And added `:nth-last-of-type` to the list of supported pseudo-classes in the
README.
Part of #747.
> [TASK] Test :nth-last-of-type

- README.md
- Move pseudo-elements and dynamic pseudo-classes to separate list of ‘what is
copied to a `<style>` element because it can’t be inlined’, removing
no-longer-relevant “some of them will never be supported”;
- Mention the pitfalls of the `…-of-type()` selectors in the ‘not implemented
yet’ section;
- Mention that any (static) pseudo-classes not claimed to be supported will have
their rules preserved and copied to a `<style>` element.
- Correct “@media queries” to “`@media` rules” and remove obsolete “now”;
- Mention that declarations in `@media` rules may need `!important`, with
example;
- Add caveat note about pseudo-elements and dynamic pseudo-classes being treated
similarly to `@media` rules, with the same possible need for `!important`;
- Replace nonsensical observation about `<link>` …
> [TASK] Update unsupported selectors & caveats in README

- CHANGELOG.md
- README.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Added a “broken: …” comment placeholder to indicate that support for `:any-link`
with the Symfony CssSelector component has been checked and found to be lacking,
suggesting tests to be added if and when it is supported in future.
Added test to confirm rules with `:any-link` are nonetheless copied to a
`<style>` element.  Also added similar tests for `:nth-last-child`,
`:nth-last-of-type` and `:only-child` with the `Emogrifier` class (these are
fully supported only with the `CssInliner` class).
In the README, added `:any-link` to a list of unsupported static pseudo-classes
that are copied to a `<style>` element rather than being inlined.
Part of #748.
> [TASK] Test :any-link

- CHANGELOG.md
- README.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Added a “broken: …” comment placeholder to indicate that support for
`:only-of-type` with the Symfony CssSelector component has been checked and
found to be broken (see https://github.com/symfony/symfony/issues/33773),
suggesting tests to be added when it is fixed.
(It does not make sense to support a feature that is broken the way it is – for
email clients that support `:only-of-type`, the desired result will currently
only be achieved if rules involving it are copied to a `<style>` element, rather
than being only partially inlined.)
Added test to confirm rules with `:only-of-type` are copied to a `<style>`
element.
In the README, added `:only-of-type` to the list of unsupported static
pseudo-classes that are copied to a `<style>` element rather than being inlined.
Part of #748.
> [TASK] Test :only-of-type

- tests/Unit/CssInlinerTest.php
This will help more quickly diagnose why a particular test might have failed.
> [TASK] Show XPath expression for test failures

- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
Tests that are not about the complete rendered HTML (and also not
explictly about the `render()` method) now use the `renderBodyContent()`
method instead in order to better communicate that they are not about
the complete HTML.
Resolves #213
> [TASK] Only render the body for most tests

- CHANGELOG.md
- composer.json
This reduces the probability of dependency conflicts with other packages.
`symfony/css-selector` 2.8 is the first version that provides the
functionality required by Emogrifier.
> [TASK] Relax the dependency on symfony/css-selector

- CHANGELOG.md
- README.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Added a “broken: …” comment placeholder to indicate that support for `:required`
and `:optional` with the Symfony CssSelector component has been checked and
found to be lacking, suggesting tests to be added if and when it is supported in
future.
Added tests to confirm rules with `:required` or `:optional` are nonetheless
copied to a `<style>` element.
In the README, added `:required` and `:optional` to the list of unsupported
static pseudo-classes that are copied to a `<style>` element rather than being
inlined.
Closes #748.
> [TASK] Test :optional and :required

- README.md
Added “`:first-of-type` (without a type)” and “`:last-of-type` (without a type)”
to unsupported selectors list – missed in #757/#758.
> [CLEANUP] Clarify :…-of-type support in README

- phpcs.xml.dist
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
The latest version of PHP_CodeSniffer now supports PSR-12,
which supersedes PSR-2.
> [TASK] Also sniff the code against the PSR-12 standard

- .travis.yml
- CHANGELOG.md
- composer.json
Now PHP >= 7.0 is required.
Changes to the code and to the php-cs-fixer configuration will come
in separate changes.
> [TASK] Drop support for PHP 5.6

- CHANGELOG.md
- README.md
- tests/Unit/CssInlinerTest.php
Looks like I was initially mistaken in believing these were not supported with
Symfony CssSelector (#743).  Looking again, I find that they are, so have added
the missing tests and updated the README accordingly.
> [CLEANUP] Test universal selector with combinators

- composer.json
The required version of that package needs to work with PHP 7.0
as long as run out tests with PHP 7.0.
> [BUGFIX] Lower the slevomat/coding-standard requirement

- CHANGELOG.md
- composer.json
uses jakub-onderka/php-parallel-lint to run `php -l` on windows without using the git for windows cli (git bash)
> Support `ci:php:lint` on Windows, fixes #740

- CHANGELOG.md
- composer.json
During development, if something is a bit awry, it’s likely that a whole bunch
of tests will fail, producing reams of output about all the failures.  In this
situation, it’s preferable to be able to run the tests so that they will stop on
the first failure.
The name of the script is deliberaly short – it needs to be manually typed (at
least once), often in frustration!
> [FEATURE] Composer script for PHPUnit with --stop-on-failure

- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
We now use the namespaced classes in all places.
> [CLEANUP] Stop using replaced PHPUnit classes

- .travis.yml
- CHANGELOG.md
- composer.json
- psalm.baseline.xml
- psalm.xml
separate PR made as per discussion in #778
> [TASK] Check the code with psalm 

- CHANGELOG.md
- config/php-cs-fixer.php
regarding: #791, https://github.com/MyIntervals/emogrifier/pull/778#discussion_r330913843
> [TASK] disable php-cs-fixer yoda conditions

- psalm.baseline.xml
- src/HtmlProcessor/HtmlPruner.php
This commit resolves the UndefinedMethod issues identified in
src/HtmlProcessor/HtmlPruner.php by altering the type hints to match
the child type of DOMNode more closely matching what is expected.
regarding: #537
> [CLEANUP] Fix psalm issues in HtmlPruner

- psalm.baseline.xml
~This commit resolves a set of MixedArgument issues.
This commit *should* be type-hinting the closure parameter via
`@psalm-param array{0:string, 1:string, 2:string, 3:string} $matches`,
but as of vimeo/psalm 3.2.12, this raises a MixedArgumentTypeCoercion
issue.~
~regarding: #537, #793~
regarding: #806, https://github.com/MyIntervals/emogrifier/pull/802#pullrequestreview-298296128
> [TASK] track issues relating to php 7.1

- .travis.yml
Now the name of the environment variable is not cut off in the
Travis CI job status list anymore.
> [TASK] Shorten a variable name in the Travis CI configuration

- composer.json
The package "slevomat/coding-standard" in version >= 4 requires
PHP >= 7.1. Due to a stale Composer cache in Travis CI, the build for
PHP 7.0 still passed with that requirement.
Now Emogrifier uses version 3.3 of that package, allowing the dev
dependencies to install again.
> [BUGFIX] Restore PHP 7.0 compatibility in the dev dependencies

- tests/Unit/CssInlinerTest.php
With the latest version of PHP_CodeSniffer, we can have boolean operators
in the middle of a line as well. This allows us more liberties with code
formatting in order to make to the code more readable.
> [CLEANUP] Reformat the code a bit

- .travis.yml
- CHANGELOG.md
- composer.json
> [FEATURE] Add support for PHP 7.4

- .github/workflows/ci.yml
- .travis.yml
- CHANGELOG.md
This should speed up the build and reduce our hassle with Travis CI.
Part of #818.
> [TASK] Move the PHP code sniffing to GitHub actions

- .github/workflows/ci.yml
- CHANGELOG.md
Providing the PHP version in the strategy matrix is not enough;
the PHP version also needs to be activated using a dedicated
action.
https://github.com/marketplace/actions/setup-php-action
Fixes #835
> [BUGFIX] Actually use the specified PHP version on GitHub actions

- .github/workflows/ci.yml
This way, we can avoid code duplication in the GitHub actions
configuration file several commands that use the same PH Pversion,
run `composer install`, cache the packages and execute a command.
More static analysis commands will be added later.
> [CLEANUP] Provide static analysis commands via GitHub actions matrix

- .github/workflows/ci.yml
- .travis.yml
- CHANGELOG.md
> [TASK] Move the composer validate from Travis CI to GitHub actions

- CHANGELOG.md
- composer.json
The package `jakub-onderka/php-parallel-lint` seems to not be
maintained anymore. Hence, we now use the well-maintained fork
`grogy/php-parallel-lint`.
> [TASK] Switch the parallel linting to a maintained fork

- .github/workflows/ci.yml
- CHANGELOG.md
Now the matrix keys for the "static analysis" GitHub actions job
are short enough so that they do not get truncated in the GitHub
actions UI, making our CI more usable.
> [BUGFIX] Make the static analysis steps visible again

- CHANGELOG.md
- src/HtmlProcessor/CssToAttributeConverter.php
- tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
This fixes an issue where if you have a width like 33.33%, the mapWidthOrHeightProperty will not correctly detect it and the style cannot be converted into an attribute.
> Fix mapping width/height when decimal is used

- .github/workflows/ci.yml
- .travis.yml
- CHANGELOG.md
Removing the Travis CI integration will follow in a separate commit.
Part of #818
> [TASK] Move the unit tests from Travis CI to GitHub actions

- CHANGELOG.md
- composer.json
Now only Symfony versions are supported that are either actively
maintained or at least receive security fixes.
This reduces the risk of being impacted by bugs that are long fixed.
For a list of supported Symfony versions, see:
https://symfony.com/releases
> [TASK] Drop support for obsolete Symfony versions

- CHANGELOG.md
- src/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Also test around the issue.
Resolves #844.
> [BUGFIX] Add `<head>` element despite `<header>`

- CHANGELOG.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
The example given in the documentation using `disableStyleBlocksParsing()` will
now actually work.
Fixes #824
> [TASK] Allow chaining all configuration methods

- psalm.baseline.xml
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
In tests for `AbstractHtmlProcessor`, ignore whitespace differences in the outer
`<html>` element.
This will help with #831.
Also added test that the `<body>` content passed to `fromHtml()` is preserved
and returned by `render()`.
> [CLEANUP] Whitespace-agnostic HTML test comparison

- CHANGELOG.md
- composer.json
We now provide the path for the development tools within `vendor/bin/`.
This avoids system-installed versions of the same tools (e.g., PHPUnit)
from getting called instead (which might be a different version and
also might not use our Composer autoloader).
> [BUGFIX] Make sure to use the Composer-installed development tools

- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Remove XHTML document types (which are not supported) from test datasets,
replacing with HTML 4.01 document types, and adding HTML 3.2 document type for
completeness.
Closes #859.
> [CLEANUP] Test only supported DOCTYPEs

- CHANGELOG.md
- composer.json
If the path-to-executable part of a command contains Unix-style path separators
(which are supported on Windows), it must be enclosed in double quotation marks
to work on Windows.
> [BUGFIX] Enquote development tool paths for Windows

- CHANGELOG.md
- src/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Ensure that the DOCTYPE declaration consists of uppercase `DOCTYPE` and
lowercase root element name (`html`).
This is done when the `DOMDocument` is created from an HTML source.  Once the
`DOMDocument` has been created, the `DOMDocumentType` cannot be changed, so the
document type declaration must be manipulated (if necessary) in the HTML
beforehand.  (Since only HTML documents are supported, the declaration is only
normalized when the root element name is HTML, in whatever case - the precise
specification for any element name involves lists of various Unicode character
ranges which it would be superfluous to allow for and try to match.  PHP's
`DOMDocument`/`libxml` itself will output the `DOCTYPE` keyword in uppercase in
any case.)
This normalization is consistent with the relevant part …
> [TASK] Normalize the DOCTYPE declaration

- CHANGELOG.md
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Verify that optional implicit tags can be omitted from the input HTML (body) in
accordance with the specification.
Although this, in reality, is testing the 3rd party DOM parser used, rather than
our code base, having these tests would allow us to choose to use a different
DOM parser with greater confidence.
Relates to #831.
> Test tag omission in conformant HTML

- CHANGELOG.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
This is the follow up to issue https://github.com/MyIntervals/emogrifier/issues/869.
The code was tested on one of my current projects and there all `@font-face` rules were successfully extracted and injected into the `<styles>` element.
Let me know if I can do something else to get this into master.
> Extract font-face rules and inject into head <styles> element

- CHANGELOG.md
- README.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
This simply broadens the range of exceptions thrown by `symfony/css-selector` (for unsupported selector expressions) which will be caught and discarded in non-debug mode.
It does not make anything magically work which didn't previously; however, it does allow the rest of the CSS to achieve full functionality, with only the affected CSS rule and selector suffering.
The tests and changes to the README clarify and correct-as-documented the current behaviour for these edge cases, which could be improved upon in future.
These are currently rarely-used CSS pseudo-classes; their level of support in mainstream browsers has only [recently reached 95% of audiences](https://caniuse.com/#search=last-of-type).  Their level of support in email clients is likely to be drasitcally lower per se for some …
> [BUGFIX] Avoid exception with :last-of-type etc.

- CHANGELOG.md
- composer.json
`grogy/php-parallel-lint` is no longer maintained.
Fixes #883
> [BUGFIX] Switch to a maintained package for parallel PHP linting

- src/CssInliner.php
- src/HtmlProcessor/AbstractHtmlProcessor.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/HtmlProcessor/HtmlPruner.php
- tests/Unit/Utilities/CssConcatenatorTest.php
We now always have the `void` return type declaration, and the
annotation nevers adds any additional information that cannot be
expressed with a return type declaration.
> [TASK] Drop @return void annotations

- CHANGELOG.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
All at-rules that have no special handling by Emogrifier will now by copied to a
`<style>` element.  Previously, Emogrifier would attempt to process them as
regular CSS rules, causing an exception in `CssSelectorConverter::toXPath()`,
which in 'debug' mode would be propagated; in either case they would be
discarded.
The rationale is that if any such rules are in the supplied CSS, they are
desired in the resulting HTML.  Emogrifier can treat them as a black box it
knows nothing about, simply to be passed on.
For at-rules which are containers for regular CSS rules (e.g. `@supports`), the
ordering could be important.  For now, these rules will be placed at the start
of the `<style>` element, so it is possible that they will be overridden by
other uninlinable rules that are placed after them, …
> [BUGFIX] Preserve all uninlinable CSS at-rules

- CHANGELOG.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
Minified selectors such as `ul>:hover` would cause an exception in debug mode,
and otherwise would always be copied to the `<style>` element even if they could
never match anything, whereas, e.g., `ul > :hover` would be treated as intended.
> [BUGFIX] Support minified combinator with pseudo-component

- CHANGELOG.md
- config/php-cs-fixer.php
Using a leading backslash when calling a function in the global namespace
provides a (small) performance benefit.
Adjust the PHP CS Fixer configuration to add any missing backslashes.
> [TASK] Automatically add a backslash for global functions

- .github/workflows/ci.yml
There may be a previous installation in the box on which the command is running,
but it's not guaranteed.
> [BUGFIX] Add `composer install` to GitHub action

- composer.json
- phpcs.xml
This is required for the dev tools to run with PHP 8.0.
> [TASK] Update `slevomat/coding-standard` to 6.x

- composer.json
The changes in #927 are not compatible with version 4.x.
> [CLEANUP] Require `slevomat/coding-standard` 6.x

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Constraint/StringContainsCss.php
- tests/Support/Constraint/StringContainsCssCount.php
- tests/Support/Traits/AssertCss.php
- tests/Support/Traits/TestStringConstraint.php
- tests/Unit/Support/Constraint/CssConstraintTest.php
- tests/Unit/Support/Constraint/Fixtures/TestingCssConstraint.php
- tests/Unit/Support/Constraint/StringContainsCssCountTest.php
- tests/Unit/Support/Constraint/StringContainsCssTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
This is the pattern used by PHPUnit, and provides a couple of benefits:
- Constraints can be combined with, e.g., LogicalOr (will be useful for #544);
- The message provided upon a test failure will be clearer.
Also corrected the namespace for `AssertCssTest` for consistency with other
`TestCase` classes.
> [CLEANUP] Move AssertCss logic to Constraint classes

- .github/workflows/ci.yml
- phpcs.xml
All the tools which we are using should properly support PHP 7.4 by
now, and we can benefit from the improved performance.
> [TASK] Run the static analysis tools with PHP 7.4, not 7.3

- CHANGELOG.md
- composer.json
Symfony 4.3 and 5.0 are end-of-life now.
Emogrifier still supports the Symfony LTS releases 3.4 and 4.4 as well
as the currently supported non-LTS version 5.1 (and newer 5.x versions).
Fixes #918
> [TASK] Drop support for Symfony 4.3 and 5.0

- CHANGELOG.md
- README.md
> [BUGFIX] Fix a nonsensical code example in the README

- src/CssInliner.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/Utilities/CssConcatenator.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
- tests/Unit/Utilities/CssConcatenatorTest.php
`@param`/`@return`/`@varannotations` like `array<int, string>`
are now recognized by PhpStorm's code inspection.
This will make our type annotations more concise and allows us
to switch to another static type analysis tool (e.g., PHPStan) more easily.
Fixes #913
> [TASK] Convert psalm-specific type annotations

- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
`ExpectationFailedException` is more specific than `AssertionFailedError`,
and we should use that for `@throws` annotations so that consumers of these
exceptions can react in a more specific way.
Fixes #787
> [BUGFIX] Use the most specific exception for @throws annotations

- .editorconfig
- .gitattributes
- CHANGELOG.md
This allows IDEs to automatically set the basic code formatting options.
Fixes #781
> [FEATURE] Add an .editorconfig file

- .github/workflows/ci.yml
This allows us to test compatibility with the lowest/highest versions
of all dependencies, not only the direct ones.
> [BUGFIX] Also update the dependencies when running Composer update

- tests/Support/Constraint/CssConstraint.php
- tests/Unit/Support/Constraint/CssConstraintTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
Also allow variation in whitespace around `;`.
Would be needed to switch to an alternative CSS parser like
`sabberworm/php-css-parser` which may result in the addition or removal the
optional semicolon, or whitespace around semicolons, in CSS declarations -
see #544.
> [TASK] Allow addition/removal of optional `;` in CSS tests

- tests/Support/Constraint/CssConstraint.php
"expressiom" is not a valid expression. And it's also not an
abbreviation of "expressionism".
> [BUGFIX] Fix typo in a private constant name

- tests/Support/Constraint/CssConstraint.php
- tests/Unit/Support/Traits/AssertCssTest.php
(This is in property declarations only, not selectors.)
Would be needed to switch to an alternative CSS parser like
`sabberworm/php-css-parser` which may result in the addition or removal of such
whitespace - see #544.
> [TASK] Allow variable whitespace around `:` in CSS tests

- .github/workflows/ci.yml
This avoid problems with Xdebug 3 (the version that now automatically
gets installed).
It also should speed up the build a bit.
Fixes #954
> [BUGFIX] Disable Xdebug in the CI build

- CHANGELOG.md
- composer.json
- src/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Use a regular expression to determine whether the provided HTML contains a
`Content-Type` `meta` element instead of just testing for the string
"Content-Type".  Also allow for case insensitivity.
A valid `Content-Type` `meta` element which is invalidly placed (i.e. within the
`body`) will still be determined to be valid.  This will be addressed separately
for #923.
Add the package `rawr/cross-data-providers` to the development dependencies.
This is useful to generate a matrix of combinations for test data providers.
There are a few existing instances where this could be used to replace code
effectively doing that, but which are not addressed in this commit.
Rename affected data provider methods from `xyzDataProvider` to `provideXyx`,
which is more succinct and a more commonly used …
> [BUGFIX] Allow "Content-Type" in content

- tests/Support/Constraint/CssConstraint.php
- tests/Unit/Support/Constraint/CssConstraintTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
Would be needed to switch to an alternative CSS parser like
`sabberworm/php-css-parser` which may result in some whitespace variations -
see #544.
Also added a test missing from #953 and updated a DocBlock to reflect that
change.
> [TASK] Allow whitespace variations in CSS tests

- CHANGELOG.md
- psalm.baseline.xml
- src/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
If a valid `Content-Type` `<meta>` element is present, DOM conversion will
create a `<head>` element for it even without an explicit `<head>` tag in the
HTML.
However, to be valid, it must not be in the `<body>` element.  As well as with
an explicit `<body>` start tag, the `<body>` element also begins whenever a
start tag for an element which cannot be in the `<head>` is encountered.  This
is now checked.
Fixes #923.
> [BUGFIX] Check existing Content-Type is in <head>

- psalm.baseline.xml
- src/HtmlProcessor/AbstractHtmlProcessor.php
...rather than `static::`.  Constants are by definition not intended to be
overridden.
This also clears up the `MixedOperand` issues reported by Psalm for the affected
code.
> [CLEANUP] Use self:: to access class constants

- tests/Support/Constraint/StringContainsCss.php
- tests/Support/Constraint/StringContainsCssCount.php
This communicates that these classes are not intended to be subclassed.
> [CLEANUP] Make more test-related classes final

- src/CssInliner.php
- src/HtmlProcessor/AbstractHtmlProcessor.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/HtmlProcessor/HtmlNormalizer.php
- src/HtmlProcessor/HtmlPruner.php
- src/Utilities/ArrayIntersector.php
- src/Utilities/CssConcatenator.php
- tests/Support/Constraint/CssConstraint.php
- tests/Support/Constraint/StringContainsCss.php
- tests/Support/Constraint/StringContainsCssCount.php
- tests/Support/Traits/AssertCss.php
- tests/Support/Traits/TestStringConstraint.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
- tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
- tests/Unit/Support/Constraint/CssConstraintTest.php
- tests/Unit/Support/Constraint/Fixtures/TestingCssConstraint.php
- tests/Unit/Support/Constraint/StringContainsCssCountTest.php
- tests/Unit/Support/Constraint/StringContainsCssTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
- tests/Unit/Utilities/ArrayIntersectorTest.php
- tests/Unit/Utilities/CssConcatenatorTest.php
- Drop `@author` annotation as the Git history already has this
information.
- Drop the `Test case.` comments from test cases as their purpose
already is implicit by their namespace.
> [CLEANUP] Slim down redundant class comments

- composer.json
- phpcs.xml
This allows us to use the PHAR version of PHP_CodeSniffer, getting us
one step further from dependency hell.
> [TASK] Stop using Slevomat PHPCS rules

- CHANGELOG.md
- composer.json
Symfony 5.1 has reached its end of life.
We still support all Symfony versions that still are maintained,
i.e., 3.4, 4.4 and 5.2.
> [TASK] Drop support for Symfony 5.1

- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
During review for #961, a regex change to capture the HTML before the
`Content-Type` tag drew attention to a couple of edge cases that weren't
explicitly tested for and would fail if there was a mistake in the regex
pattern:
- A newline before the `Content-Type` tag (would fail without the
`PCRE_DOTALL`/`s` modifier - while caught by another test,
`getDomDocumentWithNormalizedHtmlRepresentsTheGivenHtml`, that test was not
specifically intended for this purpose);
- A `Content-Type` tag in both the `<head>` and `<body>` (would fail without the
lazy/`?` quantifier after `.*`).
Tests have now been added to cover these.
> [TASK] Test more edge cases for Content-Type

- CHANGELOG.md
- src/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Also add tests to confirm that the `<html>` tag's attributes are preserved, and
a duplicate `<html>` tag does not arise.
Resolves #981.
> [BUGFIX] Allow line feeds within <html> tag

- src/CssInliner.php
We currently do not need the functionality of working with
array there.
> [CLEANUP] Make the preg_replace wrapper more specific

- psalm.baseline.xml
- src/CssInliner.php
This makes it possible to have type declarations and annotations,
both helping static code analysis as well as making the code easier
to understand.
Also make the type annotations of the methods called from the
anonymous functions more specific.
> [CLEANUP] Always use anonymous functions for callables

- phpcs.xml
The excluded sniffs prevent the use of `object{...}` type hints which are
supported by Psalm but not currently by PHPCS.
> [TASK] Exclude some FunctionComment sniffs

- src/Utilities/CssConcatenator.php
Psalm supports `object{}` type hints to provide type hints for the properties
of a `stdClass` object.  Using these in the DocBlocks allows various type hints
and (redundant) casts within the code to be eliminated.
PHPCS however does not currently understand them, so some DocBlock sniffs are
locally disabled for now.
> [CLEANUP] Add type hints for stdClass object properties

- CHANGELOG.md
- src/HtmlProcessor/CssToAttributeConverter.php
- tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
Since this is set for `<td>` elements, it makes sense to also set it for `<th>`
elements, as both represent table cells.  Although these attributes are
obsolete, there may still be some legacy email clients (e.g. older versions of
Outlook) that need it.
> [FEATURE] Set align attribute for <th> elements

- composer.json
This avoid warnings about using PHPUnit features that deprecated in
PHPUnit 9.
> [TASK] Pin PHPUnit to version 8

- CHANGELOG.md
- psalm.baseline.xml
- src/CssInliner.php
The cache with the key `CACHE_KEY_CSS` was storing all of the parsed CSS data
as a single entry, but would only ever be set once and never accessed.  It does
not make sense to call `inlineCss` again on the same document with the same CSS,
but in any case this method clears all caches as its first action.
This will reduce the memory footprint after `inlineCss` returns.
> [CLEANUP] Remove a redundant CSS data cache

- composer.json
- psalm.baseline.xml
These save having to remember the command line arguments and/or type a more
intricate command:
- `composer psalm:baseline`: Update the `psalm.baseline.xml` to remove any issues
that have been fixed;
- `composer psalm:cc`: Clear Psalm's cache for the project; sometimes this may
be required to resolve spurious errors that might arise after switching
between branches in the same directory.
> [FEATURE] Composer scripts for Psalm

- psalm.baseline.xml
We have pinned PHPUnit to version 8 and hence do not get warnings
for using functionality that has been deprecated in PHPUnit 9 yet.
> [CLEANUP] Drop Psalm warnings for PHPUnit 9

- src/CssInliner.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/Utilities/CssConcatenator.php
This will allow for changing the parameter or return value type (or parameter
name) with a clean commit, without having to reformat the description for 120
character line-lengths.
Also
- Align multiline `@param` and `@return` bodies with the first line (i.e. so
that each subsequent line of description (or in some cases, type) is at the
position after the space following the at-tag;
- Remove 'sentence' capitalization and full stop from some descriptions which
are not sentences;
- Move part of a parameter description for `parseCssShorthandValue` to the
method description where it belongs;
- Use backticks around parts of descriptions which are clearly code.
> [CLEANUP] Add newline in DocBlock before long descriptions

- psalm.baseline.xml
- psalm.xml
- tests/Unit/Utilities/CssConcatenatorTest.php
Psalm is not aware that `setUp` always is called before any
test method in the tests.
> [CLEANUP] Ignore warnings about unset properties in the tests

- src/CssInliner.php
- src/Utilities/CssDocument.php
- src/Utilities/ParsedCss.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Utilities/CssDocumentTest.php
Part of #734 and #544.  Relates to #994.
> [CLEANUP] Move CSS parsing to a separate class

- tests/Unit/Utilities/CssDocumentTest.php
The `@font-face` rule used for testing CSS parsing was missing a semicolon
between its properties.
Emogrifier currently passes on most of these types of at-rules unmodified,
without checking their validity too much.  Other CSS parsers might not be so
generous.
> [BUGFIX] Add missing semicolon in CSS test data

- .editorconfig
- CHANGELOG.md
Now we also have formatting options for YAML and JSON files.
> [TASK] Support more file types in the `.editorconfig`

- tests/Support/Traits/CssDataProviders.php
- tests/Unit/Support/Constraint/StringContainsCssCountTest.php
- tests/Unit/Support/Constraint/StringContainsCssTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
This means these `TestCase`s now cover their corresponding classes (as declared
by `@covers`) and not also dependant classes, which have their own `TestCase`s
now fully covering their functionality.
Also added CSS datasets for a needle found in a larger haystack, and a needle
only partially found in a haystack.
> [CLEANUP] Move CSS Constraint tests to their TestCase

- tests/Unit/Support/Traits/AssertCssTest.php
This simplifies the `TestCase` code and makes it easier to follow.
The `dataProvider` could be reused to test a shortcut method constructing a
`Constraint` (akin to `Assert::matches` or `Assert::stringStartsWith`), should
one be defined.
> [CLEANUP] Use data provider for CssCount tests

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Constraint/StringContainsCss.php
- tests/Support/Constraint/StringContainsCssCount.php
- tests/Unit/Support/Constraint/CssConstraintTest.php
- tests/Unit/Support/Constraint/Fixtures/TestingCssConstraint.php
This will allow the method, correspondingly renamed from
`getCssNeedleRegularExpressionPattern` to `getCssRegularExpressionMatcher`, to
be used more flexibly, not necessarily for finding needles in haystacks.  It
also allows slight simplifications and tightening-up of its tests.
Update the DocBlock for the method to reflect this change and previous changes.
Also now compute the regular expression version of the CSS in the `Constraint`
constructors - this will be more efficient if the `Constraint` is re-used.
> [TASK] getCssRegularExpression without delimiters

- tests/Support/Traits/CssDataProviders.php
This avoids overriding the static analysis - the type hint for a function forms
part of the 'contract'.
> [CLEANUP] Add type hint for function instead of variable

- tests/Support/Traits/AssertCss.php
- tests/Unit/Support/Traits/AssertCssTest.php
These are akin to the methods like `stringContains` provided by PHPUnit for use
(e.g.) in constructs involving `assertThat` without having to `use` the specific
`Constraint` class.
> [TASK] Add CSS Constraint construction methods

- tests/Unit/Utilities/CssDocumentTest.php
Use the CSS assertion methods to allow equivalent but non-identical
(character-for-character) resultant CSS to pass the tests.
> [TASK] Allow syntactic variations in CssDocumentTest

- .github/workflows/ci.yml
This makes sure that we know exactly which PHP versions are affected
by change that has broken something.
> [TASK] Always run the CI jobs for all supported PHP versions

- tests/Unit/Utilities/CssDocumentTest.php
Instead of asserting that the resultant CSS matches the valid CSS, assert that
it does not contain the invalid at-rule, by simply checking that `@` followed by
the rule name (of the invalid rule) is not found.  This avoids having to cater
for variations in the rendering of the valid CSS.
> [CLEANUP] Assert invalid at-rule not found

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
When testing for equivalent or needle-in-haystack CSS, allow the URL parameter
of the `@import` rule to be enclosed in quotes (single or double) or not, and/or
wrapped by the CSS `url` function or not.
Other CSS parsers may render this rule equivalently but using a slightly
different syntax.
> [TASK] Allow syntactic variation of @import

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
When creating a regular expression to match an `@import` rule for testing, don't
treat the optional whitespace before the `;` as part of the URL.
> [BUGFIX] Don't match @import with space inside quotes

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
When testing for matching CSS, allow RGB values in CSS property declarations to
be upper or lower case.
> [TASK] Allow case insensitivity in CSS RGB values

- tests/Support/Constraint/CssConstraint.php
The description was initially copied-and-pasted from a similar DocBlock, but its
new home has nothing to do with URLs.
> [CLEANUP] Remove URL reference from DocBlock

- tests/Unit/CssInlinerTest.php
Remove trailing zeros from decimal numbers in CSS test data that are unrelated
to the specifics of whether numerical equivalence is maintained.  CSS parsing
may result in such numbers being re-rendered more efficiently (i.e. `1.30`
becomes `1.3` and `1.0` becomes `1`).  The changed test data is not concerned
with this; it is for confirming uninlineable at-rules as a whole are passed on
roughly equivalently.
> [TASK] Remove irrelevant trailing zeros from test data

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
In tests, allow the parameter of the CSS `url` function to be optionally
enclosed in quotes when the CSS is rendered, provided this is possible (i.e. the
URL does not contain quotes, parentheses or whitespace).
> [TASK] Allow optional quotes in URLs in CSS tests

- tests/Unit/CssInlinerTest.php
When testing CSS property names are converted to lowercase, allowance can be
made for length units also being converted to lowercase, since they are not case
sensitive.  Some CSS parsers may re-render them as lowercase, which is fine.
> [TASK] Allow length unit to be lower-cased in tests

- tests/Support/Traits/CssDataProviders.php
Though merely expanding one parameter into two duplicates, this allows an
intermediate variable to be eliminated (or, rather, moved to the new method)
where it was/is required to provide type information for static analysis (e.g.
Psalm).
> [CLEANUP] Extract method to self-cross datasets

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
This allows, e.g., `0.5` to be rendered as `.5` in the resultant CSS or style
attributes, or vice versa.
> [TASK] Allow zero before decimal point to be optional

- tests/Support/Constraint/CssConstraint.php
This is instead of a (now) long sequence of `elseif`s, and reduces cyclomantic
complexity.  The replacements are expanded so that references to capturing
groups (like `$1`) are replaced with the `preg_quote`d match actually captured.
> [CLEANUP] Use array of CSS regex replacements

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
This is primarily currently targeted at CSS property values, allowing single
quotes to be exchanged for double quotes or vice versa (but not removed or
added), provided there are no quotes within the string.
> [TASK] Allow single or double quotes in CSS

- tests/Support/Traits/CssDataProviders.php
This is for the CSS `Constraint`s, to confirm that they won't allow the main
tests using these `Constraint`s to pass if such case-sensitive strings are
rendered differently-cased.
> [TASK] Test case-sensitivity of URLs and quoted strings

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
Apart from `@charset` which must always be lowercase, other at-rule names are
not case sensitive in CSS.  Note this is just their names (like `media` or
`import`) and not necessarily any other part of the rule.
> [TASK] Allow case-insensitivity of @-rule names

- src/CssInliner.php
This may now copy through other at-rules such as `@keyframes` and `@supports`,
which are not otherwise processed.
> [CLEANUP] Update copyUninlinableCssToStyleNode DocBlock

- CHANGELOG.md
- src/Utilities/CssDocument.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Utilities/CssDocumentTest.php
From the spec: "User agents must ignore any `@import` rule that occurs inside a
block or after any non-ignored statement other than an `@charset` or an
`@import` rule."
This implies that an invalid `@charset` rule would be an "ignored statment" and
thus not in itself mean that any following `@import` rules must be ignored.
Since valid `@charset` rules are currently simply discarded (only UTF-8 is
supported), the change is to also (similarly) dicard invalid `@charset` rules.
> [BUGFIX] Allow @import after invalid @charset

- config/phpmd.xml
We are not using it anyway as it reports false positives.
> [CLEANUP] Remove the PHPMD rule for unused private methods

- config/phpmd.xml
We actually think that long variable names can be a good thing,
and we do not want PHPMD to stop us from using them.
In order to avoid the impression of "we need to fix our code before
we can enable the commented-out rule", the rule now has been
removed from our PHPMD ruleset altogether.
> [CLEANUP] Drop an unused naming rule from the PHPMD ruleset

- .editorconfig
- use sane defaults instead of redundant settings for each file type
- add a default line length limit for all types to avoid
overeager line breaking by IDEs
- use shorter lines for Markdown to match what many projects use
- use a 2-space indent for XML files to match what PHIVE uses
when it updates its configuration file
- drop redundant comments
> [TASK] Rework the `.editorconfig`

- config/php-cs-fixer.php
The grouping follows the list of sections in the documentation at
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/rules/index.rst.
This should make the configuration file more manageable.
(This change neither removes any rules nor does it add any.)
> [CLEANUP] Group the used PHP CS Fixer rules

- CHANGELOG.md
- phpcs.xml
- src/Caching/SimpleStringCache.php
- tests/Unit/Caching/SimpleStringCacheTest.php
This class then will later be used to replace the current caching
that is based on nested arrays.
Part of #144.
> [FEATURE] Add a simple string cache

- CHANGELOG.md
- composer.json
According to https://symfony.com/releases, Symfony 5.2 has
reached its end of life.
> [TASK] Drop support for Symfony 5.2

- .github/workflows/ci.yml
- CHANGELOG.md
We will be able to remove the additional CI job once
a stable version of Symfony 6 has been released.
Fixes #1101
> [FEATURE] Test with Symfony 6 on CI

- CHANGELOG.md
- composer.json
Symfony 3.x has reached its end of life, and hence we do not need
to support it anymore either:
https://symfony.com/releases
> [TASK] Drop support for Symfony 3.x

- README.md
This link tends randomly point to any maintained release branch,
not only `main`, and hence is useless and confusing.
Fixes #1132
> [TASK] Remove the link to the unstable release from the README

- CHANGELOG.md
- composer.json
- psalm.baseline.xml
- src/Css/CssDocument.php
Fixes #1127
Also fixes parts of #1130 by removing some redundant type annotations,
and log the other Psalm warnings into the Psalm baseline so we can
fix them later.
> [TASK] Require `sabberworm/php-css-parser:^8.4.0`

- tests/Unit/Css/CssDocumentTest.php
- tests/Unit/CssInlinerTest.php
As this is a bug in a 3rd-party library, we should fix it there, and
our build should not be red in the meantime.
Part of #1129
> [BUGFIX] Disable tests that are failing due to a bug in the CSS parser

- CHANGELOG.md
- tests/Unit/CssInlinerTest.php
Starting from 70 atomic expressions, PHP will run into the nesting level
limit that was recently added to libxml:
https://gitlab.gnome.org/GNOME/libxml2/-/commit/6f1470a5d6e3e369fe93f52d5760ba7c947f0cd1
> [BUGFIX] Only support up to 69 atomic expressions in a selector

- composer.json
- phpunit.xml
Also disable the PHPUnit result caching as this is only relevant
for running failing tests first.
Fixes #1136
> [TASK] Always run the unit tests in the same order

- tests/Unit/CssInlinerTest.php
This is for tests where the CSS is not meant to be deliberately invalid.
(Found while working on #1139.)
> [BUGFIX] Correct invalid CSS in test data

- psalm.baseline.xml
- tests/Unit/Css/StyleRuleTest.php
Our previous usage violated the class contract.
> [BUGFIX] Stop using a literal string as the rule value in a test

- CHANGELOG.md
- src/Css/CssDocument.php
- src/CssInliner.php
- tests/Unit/Css/CssDocumentTest.php
- tests/Unit/CssInlinerTest.php
This partially addresses both #1139 and #1140.
However, if the CSS contains nested at-rules, the debug setting won't currently
be passed on, due to https://github.com/sabberworm/PHP-CSS-Parser/issues/127.
Some tests have been adapted to cater for an exception in debug mode with only
some of the data.
> [TASK] Pass debug setting on to CSS parser

- .github/dependabot.yml
With this configuration, GitHub's Dependabot will create PR
to update the versions of the GitHub Actions we are using in
our CI pipeline.
> [FEATURE] Add a Dependabot action for updating GitHub actions

- README.md
Also use real numbers for the affected enumeration in the README
as PhpStorm now does this automatically, and working against PhpStorm
would be too much of a hassle.
> [TASK] Include Dependabot configuration in the release checklist

- .github/workflows/ci.yml
Previously the dot-zero versions would show as integers (e.g. 8 instead of 8.0)
within the titles of the jobs, which is not quite right.
> [TASK] Treat PHP versions as strings in ci.yml

- CHANGELOG.md
- composer.json
Symfony 5.3 has reached its end of life.
> [TASK] Drop support for Symfony 5.3

- .github/workflows/ci.yml
All necessary packages now are available for PHP 8.2, and we
do not need to fake PHP 8.2 as 8.1 in the Composer configuration
in order to get the packages installed.
> [TASK] Use PHP 8.2 in CI without faking the version for Composer

- .github/dependabot.yml
We'll update our dependencies manually if and when the need arises
(as the Composer updates were the majority of the PRs by Dependabot).
Dependabot will still update the GitHub actions.
Dependabot will still create PRs for security-relevant updates, though.
Also drop the target milestone from the configuration in order to
reduce the work needed after we have released a new major version.
Fixes #1174
> [TASK] Remove the Dependabot configuration for Composer updates

- .github/workflows/ci.yml
This allows us to catch things that will break in future PHP versions, but still kind-of-work, e.g., deprecation warnings or incorrect types.
Closes #1117
> [TASK] Run the tests on CI with all warnings enabled

- tests/Support/Constraint/CssConstraint.php
`\is_callable('parent::__construct')` is deprecated in PHP 8.2.
> [BUGFIX] Replace a deprecated callable check

- CHANGELOG.md
- composer.json
For PHP 8.1 and 8.2, we need a bug fix that avoids a deprecation warning. (Symfony 5.4.0, 6.0.0 and 6.1.0 already have this fix.)
> [BUGFIX] Bump the minimum Symfony 4.4. version

- CHANGELOG.md
- README.md
- src/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
> Disable HTML formatting by default

- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- Wrapped `<li>` element in `<ul>`
- Updated text indention of the HTML code snippet
(according to https://github.com/MyIntervals/emogrifier/pull/1214/files#r1156552170)
> Format `renderPreservesOriginalHtmlFormatting` test

- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
`TRegx\DataProvider\DataProviders::cross` now expects `array<int|string, array<int, mixed>>`, rather than whatever it was previously loosely specified to.
(This does raise the question of whether tightening up the code annotation for Psalm could be considered a breaking change.  Though it only breaks the CI, not the software itself, so I guess not.)
> [BUGFIX] Accurate return type for AbstractHtmlProcessorTest data providers

- composer.json
Version 0.15 of PHIVE on Windows creates batch files within the `.phive` directory, which in turn invoke the `.phar` file installed.
PHP cannot run batch files.
The files must be executed via the shell.
(If that doesn't work, we're stuffed, and will have to stop using PHIVE.  UPDATE: it seems to work cross-platform.)
> [BUGFIX] Invoke PHIVE Phars via shell not PHP

- src/CssInliner.php
- tests/Support/Constraint/IsEquivalentCss.php
- tests/Support/Constraint/StringContainsCss.php
- tests/Support/Constraint/StringContainsCssCount.php
A mere `string` type annotation will generate errors with Psalm 5.15 (the latest version at time of writing).
> [TASK] Annotate regex patterns as non-empty-string

- src/Css/CssDocument.php
`list` means `array with numeric continuous keys starting with 0`.
> [CLEANUP] Use more specific type annotations in `CssDocument`

- src/CssInliner.php
`list` means `array with numeric continuous keys starting with 0`.
> [CLEANUP] Use more specific type annotations in `CssInliner`

- psalm.baseline.xml
- src/CssInliner.php
The type specification of `array{selector: string, line: int}` is exact. To allow arrays with other various random elements, we need `array{selector: string, line: int, ...}`
Kudos to @weirdan for help with this
(https://github.com/vimeo/psalm/issues/10188).
> [CLEANUP] Allow array subtype parameters

- psalm.baseline.xml
- src/CssInliner.php
Psalm indicates that `DOMNode::nodeValue` could be `null`, perhaps for entirely empty `<style>` elements.
If such are encountered during pre-processing, still remove them from the DOM, but don't append their contents to the CSS to be inlined with extra line-breaks.
> [BUGFIX] Skip any style elements with null value, but still remove them

- composer.json
This avoids CI failures when a new version of a dev dependency is released.
Fixes #1233
> [TASK] Pin the versions of the dev dependencies

- CHANGELOG.md
- README.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
Exclude CSS selectors from the stylesheets being inlined. This might for example prevent global CSS rules with universal selector (*) to be inlined on each node.
- Add unit tests
- Normalize selectors spaces/line breaks
- Add CHANGELOG entry
- Add README documentation
> [FEATURE] Add the ability to exclude CSS selectors from being inlined

- .phive/phars.xml
- psalm.baseline.xml
- tests/Unit/CssInlinerTest.php
Also reformat the code with the updated version of PHP-CS-Fixer.
Also recreate the Psalm baseline with the additional warnings that get detected now.
> [TASK] Update the QA tools

- config/php-cs-fixer.php
- src/Css/StyleRule.php
- src/CssInliner.php
- src/Utilities/CssConcatenator.php
- tests/Support/Constraint/CssConstraint.php
- tests/Support/Constraint/StringContainsCssCount.php
- tests/Support/Traits/TestStringConstraint.php
- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Switch to the PER2 coding standard and reduce the number of custom rules.
This basically aligns our code style with that used by the PHP-CSS-Parser project, which is very close to the PER-2 coding standard.
Fixes #1262
> [TASK] Update our coding standard

- config/php-cs-fixer.php
https://cs.symfony.com/doc/rules/strict/strict_param.html
Fixes #1267
> [TASK] Ensure functions have `$strict` set to `true`

- config/php-cs-fixer.php
As we already are doing this in our code, this added rule does not cause any changes to the code.
> [TASK] Add a PHP-CS-Fixer rule to prefer single-quoted string literals

- src/CssInliner.php
The input selector is guaranteed to be a string, so we can directly index the cache array with it. This avoids the overhead of calculating the cryptographic hash and the creation of a fresh string, makes the array more friendly for manual inspection using a debugger and avoids using a function that might be deprecated with PHP 8.4.
> [CLEANUP] Remove unnecessary `md5()` call in `CssInliner::getCssSelectorPrecedence()`

- config/php-cs-fixer.php
Ensure that parameters that have a `null` default value also have `null` as part of their type declarations.
Also ensure a uniform notation for nullable types.
https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated
Fixes #1269
> [TASK] Add a fixer rule to ensure a PHP 8.4 compatibility

- CODE_OF_CONDUCT.md
Copy version 2.1 of the contributor convenant code of conduct without any changes except those:
- use our contact email address
- drop links additional resources related to the contributor covenant CoC
https://www.contributor-covenant.org/version/2/1/code_of_conduct/
> [TASK] Update the code of conduct to version 2.1

- .github/CONTRIBUTING.md
We're not using Travis CI anymore. Also, there is no way external contributors to request reviews on pull requests.
Also update outdated URLs.
Also update the wording to be less Emogrifier-specific so we can copy'n'paste this documentation more easily to our sister project.
> [TASK] Update the contribution workflow documentation

- phpunit.xml
We still want to require the `@covers` annotation to be used for testcase (`forceCoversAnnotation="true"`), but we also want to be able to indirectly execute code that is not referenced via an `@covers` annotation.
> [TASK] Be less strict about the `@covers` annotation

- .github/workflows/codecoverage.yml
- .gitignore
- README.md
- composer.json
- phpunit.xml
> [FEATURE] Collect code coverage and add a coverage badge

- .github/dependabot.yml
If we want to have fixed versions of our development dependencies, manually updating them will be quite a hassle. Let's automate this instead using Dependabot.
> [FEATURE] Configure Dependabot to also update dev dependencies

- .github/dependabot.yml
We want to stay at PHPUnit 9.x to stay compatible with PHP 7.3.
Also, `rawr/cross-data-providers` has breaking changes in newer releases. As that package has been abandonded anyway, we won't bother with updating it and switch to the successor instead later.
> [TASK] Rein in Dependabot a bit

- phpstan-baseline.neon
- src/CssInliner.php
- src/HtmlProcessor/AbstractHtmlProcessor.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/Utilities/Preg.php
- tests/Support/Constraint/CssConstraint.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/Utilities/PregTest.php
The new class uses functionality that previously existed in `CssInliner`. The `preg_replace` wrapper is extended to also support arrays as the `$pattern` and `$replacement` parameters, and to support the `$limit` and `$count` parameters.  A `preg_replace_callback` wrapper is also added.
With these methods in a separate class, they can be independently tested, which is duly done.
All calls to `preg_replace` and `preg_replace_callback` are changed to use the new class.  This resolves a number of PHPStan errors.
> [CLEANUP] Add class for `preg_ function` error handling

- src/Utilities/Preg.php
- tests/Unit/Utilities/PregTest.php
This flag is not used anywhere in the current code base.  It causes complications with static analysis due to its introduction of a dynamic return type for `preg_split`, which would require a PHPStan extension to properly solve (and which assumes PHPStan would always be used as the static analysis tool).
> [TASK] Remove support for PREG_SPLIT_OFFSET_CAPTURE from Preg::split

- phpstan-baseline.neon
- src/CssInliner.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/HtmlProcessor/HtmlPruner.php
This resolves three PHPStan errors.
Instances of calls to `preg_split` in the two (identical) `parseCssDeclarationsBlock` methods are not updated - those are covered separately by #1311.
> [CLEANUP] Use Preg::split to handle unexpected preg_split errors

- phpstan-baseline.neon
- tests/Support/Traits/CssDataProviders.php
PHPStan is able to determine that `array_combine` when passed the results of `array_keys` and `array_values` for the same array can never fail (in the sense of returning `false`), because the two passed arrays will always be the same length.
Psalm could not, which was why the return value check and `throw` was originally put in.
> [CLEANUP] Remove an impossible `throw`

- phpstan-baseline.neon
- src/CssInliner.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/Utilities/DeclarationBlockParser.php
- tests/Unit/Utilities/DeclarationBlockParserTest.php
This is essentially a refactoring to move the `parseCssDeclarationsBlock` method that was duplicated in both `CssInliner` and `CssToAttributeConverter` to a separate class.
As well as eliminating duplicate code/functionality, there are other benefits:
- The method can be tested independently, which is duly done;
- The results cache is now shared;
- The functionality is readily available to other classes, e.g. for the solution to #1276 (as currently proposed).
PHPStan errors from the original code have been resolved as follows:
- Use `Preg::split` to wrap `preg_split` to handle unexpected errors;
- Check the return value from `preg_match` precisely with `!== 1` instead of `!`.
Longer-term, we should be able to use functionality from PHP-CSS-Parser for more accurate parsing (e.g. strings …
> [CLEANUP] Add DeclarationBlockParser class

- phpstan-baseline.neon
- src/CssInliner.php
This `private` method provides functionality that is used in three separate places (albeit a one-liner), and includes taking care of exception handling according to the debug mode setting.
The new method and parameter names match the equivalent in the [Web API](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll).
There will be a tiny performance impact due to additional method calls.  But the benefits include code re-use and common error handling.
Also add `ensureNodeIsElement` method for use with the result from `querySelectorAll` to ensure type safety.  `querySelectorAll` should always return a `DOMNodeList` of `DOMElement`s.  But this cannot be guaranteed if there is a bug in CssSelector whereby it returns an XPath expression which may match non-element nodes. …
> [CLEANUP] Add `CssInliner::querySelectorAll` method

- src/Utilities/DeclarationBlockParser.php
This was added during development while `Preg::split` supported `PREG_SPLIT_OFFSET_CAPTURE` and thus could return an array of arrays, and the code contained a check for this.  But before #1311 was completed, #1313 was implemented to avoid the headache of a dynamic return type.  The check was removed, but not the corresponding comment explaining it.
> [CLEANUP] Remove inapplicable comment in DeclarationBlockParser::parse

- tests/Unit/Utilities/PregTest.php
Also remove the error suppression operator.
This was overlooked #1313 when a new test method replaced another, but retained some of its code.
> [CLEANUP] Use valid example in PregTest for split with offset capture

- src/Utilities/Preg.php
- tests/Unit/Utilities/PregTest.php
This will allow code using `preg_match` to be written more cleanly.
> [TASK] Add `Preg::match` to wrap `preg_match` with error handling

- phpstan-baseline.neon
- src/Css/CssDocument.php
- src/CssInliner.php
- src/HtmlProcessor/AbstractHtmlProcessor.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/Utilities/DeclarationBlockParser.php
- tests/Support/Constraint/CssConstraint.php
- tests/Support/Constraint/IsEquivalentCss.php
- tests/Support/Constraint/StringContainsCss.php
- tests/Unit/Css/CssDocumentTest.php
For consistency with the return value being the number of matches, even though (unlike with `preg_match_all`) it can only be 0 or 1, code instances testing the result are changed to always use `=== 0` or `!== 0`.
This resolves several PHPStan errors.
> [CLEANUP] Use Preg::match to handle unexpected preg_match errors

- tests/Unit/Utilities/PregTest.php
They are now grouped by the method tested, apart from tests for the exception switch, which cover all methods at once.
> [CLEANUP] Reorder methods in PregTest

- src/Utilities/Preg.php
- tests/Unit/Utilities/PregTest.php
This completes the set of wrappers for `preg_` functions that might unexpectedly fail, and which are used in the codebase.
> [TASK] Add `Preg::matchAll` to wrap `preg_match_all` with error handling

- src/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
This is `protected` so that it can be used by subclasses, e.g. for iterating the DOM tree (which is likely for #1276).
> [TASK] Add `AbstractHtmlProcessor::getHtmlElement()`

- README.md
"valuable" -> "applicable"
Valuable usually means a high price tag when traded.  I think "applicable" is what was really meant, i.e. to imply that those that are relevant are kept, whilst those not are discarded.
> [CLEANUP] Improve README wording re `@media` rules

- CHANGELOG.md
- README.md
- config/phpmd.xml
- src/HtmlProcessor/CssVariableEvaluator.php
- tests/Unit/HtmlProcessor/CssVariableEvaluatorTest.php
Add a new `HtmlProcessor` class that can evaluate CSS custom properties (variables) after CSS which uses them has been inlined.
Resolves #1276, though an additional feature to remove unused variable definitions after evaluation could be provided.
> [FEATURE] Support CSS custom properties

- src/Caching/SimpleStringCache.php
- src/Css/CssDocument.php
- src/Css/StyleRule.php
- src/CssInliner.php
- src/HtmlProcessor/CssToAttributeConverter.php
- src/HtmlProcessor/CssVariableEvaluator.php
- src/HtmlProcessor/HtmlNormalizer.php
- src/HtmlProcessor/HtmlPruner.php
- src/Utilities/ArrayIntersector.php
- src/Utilities/CssConcatenator.php
- src/Utilities/DeclarationBlockParser.php
This pull request addresses issue [#1339](https://github.com/MyIntervals/emogrifier/issues/1339) by explicitly marking several classes in the codebase final.
Classes made final:
* `src/Caching/SimpleStringCache.php`
* `src/Css/CssDocument.php`
* `src/Css/StyleRule.php`
* `src/CssInliner.php`
* `src/HtmlProcessor/CssToAttributeConverter.php`
* `src/HtmlProcessor/CssVariableEvaluator.php`
* `src/HtmlProcessor/HtmlNormalizer.php`
* `src/HtmlProcessor/HtmlPruner.php`
* `src/Utilities/ArrayIntersector.php`
* `src/Utilities/CssConcatenator.php`
* `src/Utilities/DeclarationBlockParser.php`
> Mark classes as final

- .github/workflows/require-tests.yml
This pull request addresses issue #1259 by adding the  [infection/tests-checker-action](https://github.com/infection/tests-checker-action) GitHub Action that ensures tests are included in pull requests.
Changes Introduced:
- `.github/workflows/require-tests.yml`: Added a workflow named `Require Tests on Code Change` that uses the `infection/tests-checker-action` to verify the presence of test files in the `tests` directory with a specific pattern (`*Test.php`).
> Add GitHub Action to Require Tests in Pull Requests

- phpunit.xml
PHPUnit by default chooses the correct bootstrap. So we don't need to specify it.
> [TASK] Drop a redundant PHPUnit configuration option

- phpunit.xml
PHPUnit result caching is not related to performance, but only to running failed tests only (which is a feature we don't use).
Disabling the PHPUnit result cache keeps the result cache files from littering the project directory.
> [TASK] Don't cache the PHPUnit results

- phpunit.xml
This gets rid of the 9-space indentation and also will make diffs cleaner in the future.
> [CLEANUP] Reformat the PHPUnit configuration file

- CONTRIBUTING.md
This will allow autoformatting when we do changes without introducing unrelated formatting changes.
> [CLEANUP] Autoformat `CONTRIBUTING.md`

- CHANGELOG.md
- composer.json
This is required to ensure compatibility up to PHP 8.4 even with the lowest permitted dependencies.
> [TASK] Require `sabberworm/php-css-parser:^8.7.0`

- CHANGELOG.md
- composer.json
We'll raise the minimum required bugfix versions for Symfony in a separate change to ensure PHP 8.4 compatibility even with the lowest dependencies.
Fixes #1242
> [TASK] Drop support for Symfony 4.4

- CONTRIBUTING.md
- composer.json
- always use the `fix:` prefix for all fixing-related Composer scripts
- add a `fix` script to conveniently run all fixers
- add a missing script description
> [TASK] Make the Composer scripts for fixing things more consistent

- .github/workflows/ci.yml
- CHANGELOG.md
- composer.json
These Symfony versions are PHP-8.4-compatible:
- 7.1.0
- 7.0.3
- 6.4.3
- 6.3.12
- 6.2 (none)
- 6.1 (none)
- 6.0 (none)
- 5.4.35
The relevant thing is whether the `CssSelector/XPath/Translator.php` class does not use implicit nullable parameters anymore.
So we'll need to drop support for Symfony 6.0 through 6.2 altogether and raise the minimum required bugfix versions of the other minor versions.
Fixes #1359
> [TASK] Drop support for Symfony versions without PHP 8.4 support

- .github/workflows/ci.yml
- composer.json
- config/rector.php
Also rename the `fix:php` script to be more specific now that we have two PHP-related fixing scripts.
Fixes #890
> [FEATURE] Add Rector to our development toolchain

- CONTRIBUTING.md
So far, we had a mixture of `bash` and `shell`. Let's unify this.
> [CLEANUP] Make the Markdown code highlighting consistent

- tests/Support/Traits/CssDataProviders.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
> [TASK] Use more native types in the tests

- composer.json
This is the first step of migrating from the abandoned `rawr/cross-data-providers` package to this package.
Part of #1219
> [TASK] Add `rawr/phpunit-data-provider` as a dev dependency

- .github/dependabot.yml
- composer.json
- phpstan-baseline.neon
- phpstan.neon
We'll allow `assertInstanceOf` checks in the tests again in a later change.
> [TASK] Upgrade to PHPStan 2.x and Rector 2.x

- .gitattributes
- composer.json
- config/phpstan-baseline.neon
- config/phpstan.neon
Move the configuration and baseline files to `config/` in order to declutter the project main directory (following our sister project).
Stop using the GitHub formatter as this makes it impossible for humans to see any errors if the CI pipeline fails.
> [TASK] Move and polish the PHPStan configuration and scripts

- .github/workflows/ci.yml
> [TASK] Drop unused GPG keys from `phive install` on CI

- CONTRIBUTING.md
> [TASK] Polish the git rebasing section in `CONTRIBUTING.md`

- .github/workflows/ci.yml
- .phive/phars.xml
- composer.json
The PHIVE version is no longer installable due to the GPG key not being available any more. Also, we can now install it via Composer just fine.
> [TASK] Move PHPMD from PHIVE to Composer

- README.md
- docs/release-checklist.md
> [DOCS] Move the release checklist out of the README

- composer.json
- config/phpstan.neon
This is an opiniated set of PHPStan rules to make code more explicit and intuitive to read.
https://github.com/rectorphp/type-perfect
As our code already is in pretty good shape, this new set of rules does not add any new warnings to our baseline.
> [TASK] Add PHPStan rules from Rector Type Perfect

- config/phpstan-baseline.neon
- tests/Support/Traits/CssDataProviders.php
- tests/Unit/Support/Constraint/IsEquivalentCssTest.php
Let's reduce cognitive complexity to make the lives of the poor developers a bit easier.
This is in preparation to migrating more data providers to the new `rawr/phpunit-data-provider` package.
> [CLEANUP] Reduce callbacks for data providers in the tests

- config/phpmd.xml
- src/Css/StyleRule.php
This paves the way towards PHP-CSS-Parser V9 compatibility.
> [BUGFIX] Avoid deprecated string casts

- tests/Support/Traits/CssDataProviders.php
This change avoids the nested `array_map` calls and makes the data provider shorter and easier to understand.
Also, not using `array_*` functions paves the way towards switching to `rawr/phpunit-data-provider`, which returns iterables instead of array (which means that we cannot use array functions on the results provided by that library's methods).
Part of #1317
> [CLEANUP] Simplify a data provider

- tests/Support/Traits/CssDataProviders.php
> [TASK] Migrate to `DataProvider::cross()` in one more testcase

- config/phpstan-baseline.neon
- src/Css/CssDocument.php
This change avoids conflicts with the latest version of the CSS parser by trusting its type annotations more.
> [CLEANUP] Drop unnecessary `@var` annotations

- config/rector.php
The removed rule already is part of one of the rulesets we use.
> [CLEANUP] Drop redundantly-registered Rector rule

- src/Css/CssDocument.php
- src/CssInliner.php
- src/HtmlProcessor/AbstractHtmlProcessor.php
- src/HtmlProcessor/CssVariableEvaluator.php
- tests/Unit/Utilities/PregTest.php
For nullable types, notations like `?string` are allowed only for native type declarations, but not for PHPDoc type annotations (even though they might work for some tools).
> [CLEANUP] Fix type annotations for nullable types

- CHANGELOG.md
- composer.json
This is needed for supporting PHP 8.5.
> [TASK] Require sabberworm/php-css-parser >= 9.1.0

- src/CssInliner.php
This is in preparation for using the safe versions of the preg functions.
> [CLEANUP] Refactor preg usage in `CssInliner`
