MyIntervals/emogrifier

- .travis.yml
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
- composer.json
- update PHPUnit to 4.6.x
- update and pin PHP_CodeSniffer to 2.3.x
- drop the --dev parameter from the composer install
- fix code style warnings with the new PHP_CodeSniffer
> [BUGFIX] Update dev packages and fix warnings

- README.md
> [TASK] Document that !important is not supported yet

- README.md
Added links to a couple of helpful resources regarding email client support for CSS
Added instructions for installing PHPUnit and running tests
> [TASK] Small readme updates

- Classes/Emogrifier.php
The current version number is listed in the class PHPDoc of the Emogrifier
class using the @version annotation.
Fixes #97
> [TASK] Add a parsable version number

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
This also removes the configuration option
preserveEncoding.
Fixes #98
Fixes #143
> [TASK] Stop encoding umlauts and dollar signs

- CONTRIBUTING.md
- README.md
> [TASK] Add a CONTRIBUTING.md

- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Properly handle UTF-8 characters and entities

- Classes/Emogrifier.php
The method had "return @void" instead of "@return void".
Fixes #174
> [CLEANUP] Fix the PHPDoc of fillStyleAttributesWithMergedStyles

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Fix CSS selectors with exact attribute only

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Keep CSS media queries even if followed by CSS comments

- Classes/Emogrifier.php
This is faster and also makes the intent behind the code more visible.
Fixes #185
> [CLEANUP] Use ===/!== '' instead of strlen for empty-string checks

- Classes/Emogrifier.php
- Configuration/PhpCodeSniffer/Standards/Emogrifier/ruleset.xml
- Tests/Unit/EmogrifierTest.php
> [CLEANUP] Use the short array syntax

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [FEATURE] Handle !important

- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
> [FEATURE] Allow elements to be excluded from emogrificatioin

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [FEATURE] Remove media queries which do not impact the document

- Classes/Emogrifier.php
> [CLEANUP] Make copyCssWithMediaToStyleNode private

- README.md
[ci skip]
Fixes #212
Relates #206
> [TASK] Add documentation for emogrifyBodyContent

- .travis.yml
> Update travis.yml to include encrypted oauth token

- Tests/Unit/EmogrifierTest.php
> [CLEANUP] Drop the LF after the doctype in the test

- Classes/Emogrifier.php
- Configuration/PhpCodeSniffer/Standards/Emogrifier/ruleset.xml
- Tests/Unit/EmogrifierTest.php
- composer.json
* add some sniffs from the TYPO3 sniff pool
* always use single quotes for strings when possible
* avoid unnecessary concatenation
* move the concatenation dot to the end of the line
* change if/else/elseif constructs to have only one return
* group the sniffs in the ruleset
Fixes #222
> [TASK] Add more sniffs to the CI task

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Fix parsing of CSS for data URIs

- composer.json
> [TASK] Pin the versions of the development packages

- README.md
> [TASK] Document the minimum required PHP version

- Classes/Emogrifier.php
This is the precursory cleanup before the fix for :first-child and :last-child.
> [CLEANUP] Rename things to better match the CSS specs

- Tests/Unit/EmogrifierTest.php
> [TASK] Add more test cases for data URIs

- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
> [TASK] Make HTML5 the default document type

- CONTRIBUTING.md
> [TASK] Enhance the CONTRIBUTING guidelines

- CHANGELOG.md
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Fix failing tests on Windows due to line endings

- CHANGELOG.md
> [BUGFIX] Fix MarkDown rendering of CHANGELOG.md

- CHANGELOG.md
> [BUGFIX] Release date not visible in change log

- CHANGELOG.md
> [TASK] Add changelog skeleton for 1.1.0

- Classes/Emogrifier.php
> [CLEANUP] Rename all $xpath to $xPath

- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [CLEANUP] Use more specific types for array annotations

- CHANGELOG.md
> [TASK] Also mention the PHP 5.4 removal in the 1.1 changelog

- README.md
> [BUGFIX] Adapt the TOC of the README to the headings

- Tests/Unit/EmogrifierTest.php
Also fix some smaller issues in some tests.
Fixes #275
> [CLEANUP] Format all tests according to the four-phase test

- Classes/Emogrifier.php
> [CLEANUP] Better formatting of preg_replace rules in translatesToXpath

- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
> [FEATURE] Add CSS to HTML attribute mapper

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Second !important rule needs to overwrite the first one

- CHANGELOG.md
- README.md
- composer.json
> [CLEANUP] Remove references to mbstring dependency

- .travis.yml
- Classes/Emogrifier.php
- Configuration/PhpCodeSniffer/Standards/Emogrifier/ruleset.xml
- composer.json
* drop the TYPO3 sniff pool
* update PHPUnit
* update PHP_CodeSniffer
* fix two code style warnings
* re-enable code sniffing for PHP 7
> [BUGFIX] Fix the Composer-related breakage

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> [TASK] Add a Code of Conduct

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
This fixes some noisy errors for empty media queries.
Fixes #237
Fixes #307
> [BUGFIX] Ignore empty media queries

- README.md
HI guy, I liked this lib a lot, but my developer had difficulties because he don't know composer a lot. Then I think that is good idea to add how to install by composer. Thanks
> Add Install to documentation

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Ignore value with words more than one in the attribute selector

- CHANGELOG.md
- composer.json
> [TASK] Release version 1.1.0

- CONTRIBUTING.md
- add a table of contents
- document that PRs should be made editable
- add links for PR, reviews etc.
Fixes #340
Fixes #355
> [TASK] Improve the CONTRIBUTING.md

- .travis.yml
> [CLEANUP] Use the "install" target in travis.yml

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Ignore "auto" width and height

- README.md
Creating this pull request as requested by @oliverklee [here](https://github.com/jjriv/emogrifier/issues/357#issuecomment-271084420).
> Clarify the disableStyleBlocksParsing option

- CHANGELOG.md
- Classes/Emogrifier.php
- composer.json
> [TASK] Release version 1.2.0

- composer.json
- update the homepage URL
- polish the PHP requirements formatting
- fix "tags" to "keywords"
> [CLEANUP] Streamline the composer.json

- .travis.yml
- also cache the composer cache
- disable Xdebug
> [TASK] Speed up the Travis builds

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
> [BUGFIX] Fix media regex parsing

- CHANGELOG.md
- Classes/Emogrifier.php
- Tests/Unit/EmogrifierTest.php
This is a prerequisite to #396.
> [BUGFIX] Make sure the HTML always has a BODY element

- Classes/Emogrifier.php
This clean-up is a preparation for implemention the :not selector in #395.
> [CLEANUP] Split up larger methods

- Classes/Emogrifier.php
Now a callback can be used for matching the class attributes, making
inline matching possible.
This is the final refactoring before #395.
> [CLEANUP] Refactor translateCssToXpathPass for callbacks

- Configuration/PhpCodeSniffer/Standards/Emogrifier/ruleset.xml
- composer.json
Also make use of new sniffs that make sense for Emogrifier.
> [TASK] Update PHP_CodeSniffer from 2.6.0 to 3.1.1

- Classes/Emogrifier.php
- remove unneeded paranthesis around the exception in a throw
- add more type annotations
> [CLEANUP] Minor code cleanup

- CHANGELOG.md
- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
> [FEATURE] Support the :not() selector

- CHANGELOG.md
- Classes/Emogrifier.php
This will slightly improve performance.
> [TASK] Optimize string operations

- Classes/Emogrifier.php
Originally part of PR https://github.com/MyIntervals/emogrifier/pull/425.
> [CLEANUP] Move style attributes normalization into a new private method

- README.md
This will enable syntax highlighting in Markdown rendering.
> [CLEANUP] Annotate code blocks in the README with the used language

- Classes/Emogrifier.php
- README.md
- Tests/Unit/EmogrifierTest.php
- composer.json
- also change Oliver's email address
- also fix a broken link in the README table of contents
Fixes #450
> [TASK] Add Zoli Szabó as maintainer/author

- Tests/Unit/EmogrifierTest.php
- move the adjacent matcher tests to the new structure
- move the :first-child and :last-child matchers tests to the new structure
- move the :not matchers tests to the new structure
- remove the obsolete selector test that got converted to the new structure
- move some tests around so the selector tests match the order in the README
- add more notes for broken selectors
> [CLEANUP] Simplify and clean up the test case (part 7)

- CHANGELOG.md
- Classes/Emogrifier.php
- README.md
- composer.json
> [TASK] Prepare the 2.0.0 release

- CHANGELOG.md
Also drop surplus empty lines and and empty "security" section.
> [TASK] Prepare the changelog for starting the next version

- .github/CONTRIBUTING.md
- enable syntax highlighting for code lines
- fix the broken link to CODE_OF_CONDUCT.md
> [CLEANUP] Polish CONTRIBUTING.md

- .travis.yml
- echo the current action instead of having a code comment
- reorder the steps so functionality comes first, prettiness last
- make the steps better readable in .travis.yml
> [CLEANUP] Clean up the build script in .travis.yml

- Classes/Emogrifier.php
Old name was the exact opposite to what it represented.
> [CLEANUP] Renamed flag shouldKeepInvisibleNodes -> shouldRemoveInvisibleNodes

- composer.json
Now the order reflects the current activity level.
> [TASK] Reorder the authors/maintainers in composer.json

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
For Emogrifier 3.0.0, this will be the successor of the
\Pelago\Emogrifer class.
Currently, the new class is a plain copy of the Emogrifier class,
including all deprecated methods and without and API changes.
> [TASK] Add a CssInliner class

- src/Emogrifier.php
Renamed `copyCssWithMediaToStyleNode` to `copyUninlineableCssToStyleNode` and
changed the final parameter from a string of CSS to the array of "uninlineable"
parsed CSS rule data returned by `parseCssRules`.
The method can now potentially also include rules other than @media rules in the
style element added to the document, and will do when the final changes for #280
are implemented.
> [CLEANUP] Refactor `copyCssWithMediaToStyleNode`

- src/Emogrifier.php
This reduces the cyclomatic complexity of the method and makes it
easier to read.
> [CLEANUP] Split up Emogrifier::mapComplexCssProperty

- CHANGELOG.md
- composer.json
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [CLEANUP] Use the Symfony CSS selector component

- CHANGELOG.md
- README.md
- src/Emogrifier.php
- src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
- tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
This class takes over the reponsibility of what Emogrifier did with
the `enableCssToHtmlMapping` method.
> [FEATURE] Add a CssToAttributeConverter class

- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [CLEANUP] Simplify and clean up the test case (part 8)

- .github/CONTRIBUTING.md
- .travis.yml
- CHANGELOG.md
- composer.json
- config/phpmd.xml
We will activate additional checks once the corresponding code
has been fixed to not create any warnings anymore.
Fixes #110
> [TASK] Check the code with PHPMD

- src/Emogrifier/CssConcatenator.php
This is required before #563 can be implemented.
> [CLEANUP] Add missing type hints

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
> [FEATURE] Merge #562 into CssInliner

- CHANGELOG.md
Also use HTTPS for the semver link and the new repository location for
the GitHub pull request URLs.
[ci skip]
> [TASK] Update the changelog for the 1.2.1 release

- .travis.yml
This fixes a build breakage on PHP 7.3.
> [BUGFIX] Make Travis more resilient for a missing Xdebug

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
This is the next (small) step towards making the `CssInliner`
an `HtmlProcessor`.
> [TASK] Move the XML document into `$this->xmlDocument`

- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [BUGFIX] Fix a typo in a test method name

- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
This is another step towards making `CssInline` an `HtmlProcessor`.
> [TASK] Make `CssInliner::setHtml` private

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
Nowadays, PHP's garbage collector does not need our code to reset its
class properties on object destruction anymore.
> [TASK] Drop the destructors

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [TASK] Reject empty HTML in `setHtml()`

- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
> [CLEANUP] Extract method `AbstractHtmlProcessor::createRawDomDocument`

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
Now the order should be a bit more logical.
Apart from the method order, this commit does not change anything
else at all.
Part of #554.
> [CLEANUP] Change the order of methods

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
> [TASK] Remove unprocessable tags from the DOM, not from the raw HTML

- CHANGELOG.md
- README.md
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
- src/Emogrifier/HtmlProcessor/HtmlNormalizer.php
> [TASK] Prepare the 2.1.0 release

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [BUGFIX] Keep the `style` element the `head`

- .travis.yml
- CHANGELOG.md
- composer.json
see https://github.com/MyIntervals/emogrifier/issues/639#issuecomment-445455840
I believe this needs tagging only and is good to go afterwards.
> [FEATURE] Add PHP 7.3 support (v1.2.x)

- CHANGELOG.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
This bug fix slipped in with one of the latest refactorings. Now we
also have a unit test for it.
> [TASK] Add test for automatically adding a missing DOCTYPE

- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
> [CLEANUP] Code autoformat

- CHANGELOG.md
> [BUGFIX] Fix non-UTF-8 characters in the changelog

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
The repository has been moved in the meantime. The URLs should
reflect this.
> [CLEANUP] Update repository URLs in annotations

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
> [TASK] Make the CssInliner inherit AbstractHtmlProcessor

- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
Added a test to confirm `copyUninlineableCssToStyleNode` does not have unexpected side-effects, i.e. it would produce the same result if called a second time on the same `CssInliner` instance.
This will help ensure that the solution for #668 does not create future potential maintenance issues.
> [TASK] Test copyUninlineableCssToStyleNode side-effects

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- tests/Support/Traits/AssertCss.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/EmogrifierTest.php
This will slightly improve performance.
> [TASK] Make the closures static

- CHANGELOG.md
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
- tests/Unit/EmogrifierTest.php
Also autoformat the code.
Fixes #552
> [FEATURE] Add AbstractHtmlProcessor::fromHtml

- CHANGELOG.md
- src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
> [FEATURE] Add AbstractHtmlProcessor::fromDomDocument

- CHANGELOG.md
- composer.json
- config/php-cs-fixer.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/Emogrifier/CssConcatenatorTest.php
- tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
- tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
- tests/Unit/EmogrifierTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
Also make use of the new features of PHPUnit 5.7.
Fixes #438
> [TASK] Update the development dependencies

- src/Emogrifier/CssInliner.php
- src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
- src/Emogrifier/HtmlProcessor/HtmlPruner.php
Also drop a redundant condition.
Fixes #134
> [CLEANUP] Clean up early returns

- CHANGELOG.md
- src/Emogrifier/HtmlProcessor/ArrayIntersector.php
- tests/Unit/Emogrifier/HtmlProcessor/ArrayIntersectorTest.php
> [FEATURE] Add an ArrayIntersector class

- CHANGELOG.md
- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
- src/Emogrifier/Utilities/ArrayIntersector.php
- src/Emogrifier/Utilities/CssConcatenator.php
- tests/Unit/Emogrifier/Utilities/ArrayIntersectorTest.php
- tests/Unit/Emogrifier/Utilities/CssConcatenatorTest.php
> [CLEANUP] Move utility classes to Pelago\Emogrifier\Utilities namespace

- CHANGELOG.md
- tests/Unit/CssInlinerTest.php
> [TASK] Test multiple attributes selectors

- README.md
> [TASK] Properly document the CssInliner usage

- CHANGELOG.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
Implementation for #338 in the `CssInliner` class.
> [FEATURE] Preserve `@import` rules

- CHANGELOG.md
- README.md
- tests/Unit/CssInlinerTest.php
Also updated the README to indicate this combinator is now supported.
> [TASK] Test general sibling combinator

- src/Emogrifier.php
- src/Emogrifier/CssInliner.php
This will help reduce cognitive load when reading the code, and it will
also help static code analysis.
Fixes #133
> [CLEANUP] Give an anonymous function a name

- CHANGELOG.md
- README.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [FEATURE] Support :empty

- CHANGELOG.md
- README.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [FEATURE] Support: first-of-type

- CHANGELOG.md
- README.md
- src/Emogrifier/CssInliner.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [FEATURE] Support :last-of-type

- src/Emogrifier/CssInliner.php
Now the order should make reading the class a bit easier.
Resolves #256
> [CLEANUP] Reorder the methods in the CssInliner class

- CHANGELOG.md
- README.md
- tests/Unit/CssInlinerTest.php
- tests/Unit/EmogrifierTest.php
> [TASK] Test/document addExcludedSelector with subtree

- psalm.baseline.xml
cherry-picking the commits from #778 that pertain to issues that either need to be retained until resolved by discussion on other issues, or are being retained as a result of said discussion.
> [TASK] Retain psalm issues for future review

- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
- tests/Unit/Utilities/ArrayIntersectorTest.php
- tests/Unit/Utilities/CssConcatenatorTest.php
This makes sure that only dedicated tests for a class will mark that
class as covered.
Fixes #811
> [TASK] Add @covers annotations to the test cases

- CHANGELOG.md
- composer.json
Extend symfony/css-selector requirements to include 5.x
Greetings from #SymfonyHackday
> [TASK] Upgrade to Symfony 5

- CHANGELOG.md
- add missing parenthesis
- fix an issue number in a link
[ci skip]
> [CLEANUP] Fix small errors in the changelog

- .github/workflows/ci.yml
- .travis.yml
- CHANGELOG.md
> [TASK] Move the PHPMD check from Travis to GitHub actions

- .github/workflows/ci.yml
- .travis.yml
- CHANGELOG.md
> [TASK] Move more static analysis from TravisCI to GitHub actions

- CHANGELOG.md
- README.md
> [FEATURE] Add a GitHub actions status badge to the README

- .github/workflows/ci.yml
- .travis.yml
- CHANGELOG.md
> [TASK] Move the PHP linting from Travis CI to GitHub actions

- CHANGELOG.md
- README.md
- composer.json
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
> [FEATURE] Support :only-of-type

- CHANGELOG.md
- phpcs.xml.dist
- src/CssInliner.php
Also added some recently omitted of such.
Resolves #857.
> [TASK] Sniff for missing return type annotations

- CHANGELOG.md
- README.md
- composer.json
> [TASK] Prepare release of version 4.0.0

- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
- tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
- tests/Unit/Utilities/ArrayIntersectorTest.php
- tests/Unit/Utilities/CssConcatenatorTest.php
This communicates that these classes are not intented to be subclassed.
> [CLEANUP] Make the test cases final

- CHANGELOG.md
- phpcs.xml
- tests/Unit/CssInlinerTest.php
This is now possible since we require PHP >= 7.1.
> [TASK] Enforce constant visibility

- CHANGELOG.md
- composer.json
- config/php-cs-fixer.php
- tests/Unit/CssInlinerTest.php
- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
- tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Also pin `vimeo/psalm` to avoid automatic updates that are now
possible due to the changed PHPUnit dependencies.
> [TASK] Upgrade to PHPUnit 7.5

- CHANGELOG.md
- composer.json
- psalm.baseline.xml
- src/CssInliner.php
- src/HtmlProcessor/HtmlPruner.php
Also regenerate the baseline and fix the issues that cannot be covered
by the baseline.
> [TASK] Upgrade Psalm

- src/CssInliner.php
> [CLEANUP] Extract method CssInliner::hasUnsupportedPseudoClass

- src/CssInliner.php
> [CLEANUP] Extract method CssInliner::removeSelectorComponents

- CHANGELOG.md
- README.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
> [BUGFIX] Copy rules with :...of-type without type to <style> element

- CHANGELOG.md
- composer.json
- phive.xml
> [TASK] Move Psalm to Phive

- config/phpmd.xml
Our code still does not pass some of the disabled rules, but we can
enable those rules which our code now passes with the recent
refactorings.
> [TASK] Enable more PHPMD rules

- .github/workflows/ci.yml
This fixes a warning when running the CI build.
Fixes #931
> [BUGFIX] Explicitly set the Ubuntu version for GitHub Actions

- .github/workflows/ci.yml
> [TASK] Use the latest version of the GitHub git checkout action

- .github/workflows/ci.yml
- CHANGELOG.md
This allows us to catch problems that are related to changes in the
build environment or the dependencies instead of in our code,
but that probably need fixing from our side.
Fixes #932
> [FEATURE] Also run the CI build once a week

- CHANGELOG.md
Also fix the casing of "PHIVE" in the changelog.
Closes #878
> [TASK] Prepare release of version 5.0.0

- CHANGELOG.md
- README.md
- composer.json
Also drop trailing whitespace from the README.
Closes #908
> [TASK] Switch the default branch from master to main

- .github/workflows/ci.yml
This makes sure we can reap the performance and traffic benefits
of Composer 2.
> [TASK] Explicitly use Composer 2 in the CI builds 

- phive.xml
- psalm.baseline.xml
Also regenerate the baseline, but do not fix any code issues
(new or pre-existing).
Fixes #943
> [TASK] Upgrade Psalm to version 4.7

- .github/workflows/ci.yml
- CHANGELOG.md
- composer.json
> [TASK] Drop support for PHP 7.1

- src/CssInliner.php
- tests/Support/Traits/TestStringConstraint.php
- tests/Unit/CssInlinerTest.php
This will slightly improve performance.
> [CLEANUP] Make closures static

- CHANGELOG.md
This will relieve us of the error-prone task of having to manually
create issue and pull request URLs in the future.
This also makes the changelog markdown a lot shorter.
> [CLEANUP] Use implicit issue/pull request linking in the changelog

- tests/Unit/CssInlinerTest.php
Since the library `rawr/cross-data-providers` has been added as a development
dependency (in #959), make use of it where applicable to combine datasets for
tests.  This makes the test data providers clearer and eliminates duplication
of functionality.
> [CLEANUP] Use TRegx\DataProvider\DataProviders::cross()

- psalm.baseline.xml
- src/CssInliner.php
(Apologies to GitHub user @var.)
> [CLEANUP] Remove a redundant `@var` type hint

- CHANGELOG.md
Entry for #1018 was added at bottom of list, but entries should be in
reverse-chronological order.
> [CLEANUP] Correct CHANGELOG order

- tests/Support/Constraint/IsEquivalentCss.php
- tests/Support/Traits/AssertCss.php
- tests/Support/Traits/CssDataProviders.php
- tests/Unit/Support/Constraint/IsEquivalentCssTest.php
- tests/Unit/Support/Traits/AssertCssTest.php
And associated assertion methods.
> [TASK] Add an IsEquivalentCss Constraint

- tests/Support/Constraint/CssConstraint.php
- tests/Support/Traits/CssDataProviders.php
When testing CSS consisting only of property declarations (as opposed to
complete rules), allow the final semicolon to be optional.  (Note that the
optionality of such a semicolon within complete rules is already covered.)
> [TASK] Allow optional semicolon in CSS declaration

- CHANGELOG.md
- composer.json
> [TASK] Allow installation together with Symfony 6

- tests/Unit/CssInlinerTest.php
Modify the test `inlineCssFormatsCssDeclarations` to allow removal of line
breaks between 'shadows' in the `text-shadow` property value, as there is no
requirement to preserve them.  This allows using a third party CSS parser which
may remove them.
> [TASK] Allow alternative style attribute formatting

- tests/Support/Constraint/CssConstraint.php
This avoids the added complexitiy of trying to match within a regular expression
that has been generated to match the original CSS.  Now the originally-provided
plain CSS is matched instead (for `@import` which may or may not use the CSS
`url` function and may or may not have the URL within quotes).
It also avoids having to update this if a change is made to how the CSS matcher
is generated which would affect how part of an `@import` rule is matched, as was
the case with #1058.
> [CLEANUP] Create @import matcher in initial CSS pass

- .github/workflows/ci.yml
Tests appear to pass just fine locally.
> Run CI with PHP 8.2

- CHANGELOG.md
- composer.json
> Add support for PHP 8.2 to composer.json

- phpunit.xml
This will allow us to find code which we will need to update to changes in PHP or in our dependencies.
Also order the configuration options in the PHPUnit configuration file.
Fixes #1181
> [TASK] Convert deprecations to exceptions in the tests

- config/php-cs-fixer.php
> [TASK] Replace deprecated rule in our PHP-CS-Fixer ruleset

- config/php-cs-fixer.php
https://www.php-fig.org/per/coding-style/
Fixes #1189
> [TASK] Switch PHP-CS-Fixer from PSR12 to its sucessor PER

- CHANGELOG.md
- README.md
- composer.json
We should have version 7.0.0 with PHP 8.2 support out of the door before the final PHP 8.2 will get released later this month.
> [TASK] Prepare release of version 7.0.0

- .phive/phars.xml
- psalm.baseline.xml
Also update the baseline with the newly-found warnings (which we can tackle in future changes).
> [TASK] Upgrade to Psalm 5

- .github/CONTRIBUTING.md
[This procedure](https://github.com/MyIntervals/emogrifier/issues/373#issuecomment-536631092) has had four more years of being tried and tested since originally written.
I keep referring back to it when a rebase is needed.  It never fails.
So I think it needs to be incorporated into the actual docs, rather than just sitting there as a comment.
> [TASK] Add rebasing guidance to CONTRIBUTING.md

- .phive/phars.xml
- config/php-cs-fixer.php
- psalm.baseline.xml
Also update the configuration files.
> [TASK] Update the CI tools

- .github/CONTRIBUTING.md
- fix the spelling
- convert to UTF-8
> [TASK] Streamline `CONTRIBUTING.md`

- composer.json
- phpstan-baseline.neon
Because we want our code to be as clean and reliable as possible.
> [TASK] Add extra-strict PHPStan rules

- .github/workflows/ci.yml
> [TASK] Switch static analysis for the CI jobs to PHP 8.3

- CHANGELOG.md
- README.md
- src/CssInliner.php
- tests/Unit/CssInlinerTest.php
> [FEATURE] Add support for :root pseudo-class

- .gitattributes
- CHANGELOG.md
- README.md
- docs/API-and-deprecation-policy.md
This is exactly the same change as in our sister project, PHP-CSS-Parser:
https://github.com/MyIntervals/PHP-CSS-Parser/pull/720
> [DOCS] Add an API and deprecation policy

- README.md
- src/HtmlProcessor/CssToAttributeConverter.php
"whitelist" -> "allowlist" in README and a DocBlock comment.
> [CLEANUP] Replace a racially-loaded word

- CONTRIBUTING.md
This will allow us to copy this section to our sister project without changes.
> [DOCS] Make the review section in the contribution docs more general

- CONTRIBUTING.md
We now are using the PER 2.0 coding style standard.
> [DOCS] Update the coding style section in `CONTRIBUTING.md`

- CONTRIBUTING.md
> [TASK] Polish the "git commits" section of `CONTRIBUTING.md`

- tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
> [TASK] Switch one testcase to the new data provider package

- config/phpstan-baseline.neon
- config/phpstan.neon
Level 10 is PHPStan's "up to 11", which was introduced in PHPStan 2.
https://en.wikipedia.org/wiki/Up_to_eleven
> [TASK] Raise PHPStan to level 10

- config/phpstan-baseline.neon
- config/phpstan.neon
This will help avoid it suggesting things that are only possile in later PHP versions.
> [TASK] Configure the target PHP version for PHPStan

- tests/Support/Traits/CssDataProviders.php
> [TASK] Use `DataProvider::join()` to combine data providers

- tests/Support/Traits/CssDataProviders.php
- tests/Unit/CssInlinerTest.php
> [TASK] Use `DataProvider::join()` for joining data provider data

- tests/Unit/CssInlinerTest.php
> [TASK] Migrate another data provider to `DataProvider::cross()`

- CHANGELOG.md
- composer.json
> [TASK] Require `sabberworm/php-css-parser:^9.0.0`

- .github/dependabot.yml
- CHANGELOG.md
- composer.json
> [TASK] Prepare release of version 8.0.0

- config/phpstan-baseline.neon
- src/Css/StyleRule.php
- src/CssInliner.php
> [TASK] Streamline `CssInliner`

- config/phpstan-baseline.neon
- tests/Unit/HtmlProcessor/HtmlPrunerTest.php
> [TASK] Use safe preg functions in `HtmlPrunerTest`

- config/phpstan-baseline.neon
- tests/Unit/Css/CssDocumentTest.php
> [TASK] Use safe preg functions in `CssDocumentTest`

- tests/Unit/CssInlinerTest.php
> [TASK] Use safe preg functions in `CssInlinerTest`

- tests/Support/Constraint/StringContainsCssCount.php
> [TASK] Use safe preg functions in `StringContainsCssCount`

- tests/Support/Constraint/IsEquivalentCss.php
> [TASK] Use safe preg functions in `IsEquivalentCss`
